<?PHP
/* Application language file 
   */
   
$AppLanguages = array (
'english' => array (), // 7 strings
'arabic' => array ( // 6 strings
	"All messages have been deleted" => "لقد تم مسح جميع الرسائل",
	"Saved" => "تم الحفظ",
	"Erase all messages" => "مسح جميع الرسائل",
	"Archive" => "الأرشي",
	"Last changed by %0 %1" => "��� �� ���",
	"Update" => "������ ��������",
   	"d/m/Y h:i a" => "",
),
'bahasa melayu' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Perubahan Terakhir oleh %0 %1",
	"Update" => "Kemaskini",
   	"d/m/Y h:i a" => "",
),
'bangla' => array ( // 6 strings
	"All messages have been deleted" => "সমস্ত বার্তা মুছে ফেলা হয়েছে",
	"Saved" => "সংরক্ষিত",
	"Erase all messages" => "সমস্ত বার্তা  মুছে ফেল",
	"Archive" => "আর্কাইভ",
	"Last changed by %0 %1" => "সর্বশেষ পরিবর্তন করেছেন %0 %1",
	"Update" => "হালনাগাদ",
   	"d/m/Y h:i a" => "",
),
'brasileiro/português' => array ( // 6 strings
	"All messages have been deleted" => "Todas as mensagens foram apagadas",
	"Saved" => "Gravado",
	"Erase all messages" => "Apagar todas as mensagens",
	"Archive" => "Arquivar",
	"Last changed by %0 %1" => "Última modificação em %0 %1",
	"Update" => "Atualizar",
   	"d/m/Y h:i a" => "",
),
'bulgarian' => array ( // 3 strings
	"All messages have been deleted" => "",
	"Saved" => "Записан",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Последно променен от %0 %1",
	"Update" => "Обновяване",
   	"d/m/Y h:i a" => "",
),
'català' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "Desat",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Ultim canvi fet %1 per %0",
	"Update" => "Desar",
   	"d/m/Y h:i a" => "",
),
'český' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Poslední změna provedena uživatelem %0 %1",
	"Update" => "Změnit",
   	"d/m/Y h:i a" => "",
),
'chinese' => array ( // 5 strings
	"All messages have been deleted" => "所有訊息已刪除",
	"Saved" => "已存",
	"Erase all messages" => "刪除所有訊息",
	"Archive" => "",
	"Last changed by %0 %1" => "%0到%1最近的更新",
	"Update" => "更新",
   	"d/m/Y h:i a" => "",
),
'croatian' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Zadnje promijenio %0 u %1",
	"Update" => "Osvježi",
   	"d/m/Y h:i a" => "",
),
'dansk' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Sidst ændret %0 %1",
	"Update" => "Opdater",
   	"d/m/Y h:i a" => "",
),
'deutsch' => array ( // 7 strings
	"All messages have been deleted" => "Alle Nachrichten gelöscht",
	"Saved" => "Gespeichert",
	"Erase all messages" => "Alle Nachrichten löschen",
	"Archive" => "Archiv",
	"Last changed by %0 %1" => "Zuletzt geändert von %0 %1",
	"Update" => "Okay",
   	"d/m/Y h:i a" => "d.m.Y H:i",
),
'español' => array ( // 4 strings
	"All messages have been deleted" => "",
	"Saved" => "Guardado",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "última actualización por %0 %1",
	"Update" => "Actualizar",
   	"d/m/Y h:i a" => "d/m/Y H:i",
),
'euskara' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Azken aldaketa %0(e)k %1",
	"Update" => "Eguneratu",
   	"d/m/Y h:i a" => "",
),
'français' => array ( // 7 strings
	"All messages have been deleted" => "Tous les messages ont été effacés",
	"Saved" => "Sauvegardé",
	"Erase all messages" => "Effacer tous les messages",
	"Archive" => "Archiver",
	"Last changed by %0 %1" => "Dernier changement par %0 %1",
	"Update" => "Mettre à jour",
   	"d/m/Y h:i a" => "d/m/Y H:i",
),
'galego' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Última actualización feita por %0 %1",
	"Update" => "Actualizar",
   	"d/m/Y h:i a" => "",
),
'greek' => array ( // 6 strings
	"All messages have been deleted" => "Όλα τα μηνύματα έχουν διαγραφεί",
	"Saved" => "Αποθηκεύτηκε",
	"Erase all messages" => "Διαγραφή όλων των μηνυμάτων",
	"Archive" => "Αρχειοθέτηση",
	"Last changed by %0 %1" => "Τελευταία αλλαγή από %0 %1",
	"Update" => "Ενημέρωση",
   	"d/m/Y h:i a" => "",
),
'italiano' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Ultimo cambiamento di %0 %1",
	"Update" => "Aggiorna",
   	"d/m/Y h:i a" => "",
),
'japanese' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "%0さんが%1に最終更新",
	"Update" => "更新",
   	"d/m/Y h:i a" => "",
),
'korean' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "%0님이 %1에 마지막으로 수정�",
	"Update" => "업데이트",
   	"d/m/Y h:i a" => "",
),
'magyar' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Utolsó modosítás: %0 - %1",
	"Update" => "Frissítés",
   	"d/m/Y h:i a" => "",
),
'nederlands' => array ( // 6 strings
	"All messages have been deleted" => "Alle berichten zijn verwijderd",
	"Saved" => "Opgeslagen",
	"Erase all messages" => "Alle berichten verwijderen",
	"Archive" => "Archiveren",
	"Last changed by %0 %1" => "Laatste wijziging door %0 %1",
	"Update" => "Bewaren",
   	"d/m/Y h:i a" => "",
),
'norsk' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Sidst endret av %0 %1",
	"Update" => "Oppdater",
   	"d/m/Y h:i a" => "",
),
'polski' => array ( // 5 strings
	"All messages have been deleted" => "",
	"Saved" => "Zachowane",
	"Erase all messages" => "Usuń wszystkie wiadomości",
	"Archive" => "Archiwizuj",
	"Last changed by %0 %1" => "Ostatnia zmiana dokonana przez %0 %1",
	"Update" => "Uaktualnij",
   	"d/m/Y h:i a" => "",
),
'português' => array ( // 6 strings
	"All messages have been deleted" => "Todas as mensagens foram eliminadas",
	"Saved" => "Salvo",
	"Erase all messages" => "Apagar todas as mensagens",
	"Archive" => "Arquivo",
	"Last changed by %0 %1" => "Ultima alteração feita %1 por %0",
	"Update" => "Atualizar",
   	"d/m/Y h:i a" => "",
),
'românesc' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Schimbat ultima oara de %0 %1",
	"Update" => "Actualizeaza",
   	"d/m/Y h:i a" => "",
),
'russian' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Последнее изменение от %0 %1",
	"Update" => "Обновить",
   	"d/m/Y h:i a" => "",
),
'slovenský' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Posledná zmena od %0 (%1)",
	"Update" => "Pošli",
   	"d/m/Y h:i a" => "",
),
'suomalainen' => array ( // 4 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "Poista kaikki viestit",
	"Archive" => "Arkistoi",
	"Last changed by %0 %1" => "viimeksi muuttanut %0 %1",
	"Update" => "Päivitä",
   	"d/m/Y h:i a" => "",
),
'svensk' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Senast ändrad av %0 %1",
	"Update" => "",
   	"d/m/Y h:i a" => "",
),
'türk' => array ( // 6 strings
	"All messages have been deleted" => "Tüm iletiler silindi",
	"Saved" => "Kaydet",
	"Erase all messages" => "Tüm iletileri sil",
	"Archive" => "Arşiv",
	"Last changed by %0 %1" => "Son değişiklik %0 tarafından %1 yapıldı",
	"Update" => "Güncelle",
   	"d/m/Y h:i a" => "",
),
'ukrainian' => array ( // 6 strings
	"All messages have been deleted" => "Всі повідомлення видалено",
	"Saved" => "Збережено",
	"Erase all messages" => "Видалити всі повідомлення",
	"Archive" => "Архів",
	"Last changed by %0 %1" => "Остані зміни від %0 %1",
	"Update" => "Оновити",
   	"d/m/Y h:i a" => "",
),
'việt' => array ( // 2 strings
	"All messages have been deleted" => "",
	"Saved" => "",
	"Erase all messages" => "",
	"Archive" => "",
	"Last changed by %0 %1" => "Sửa đổi lần cuối bởi %0 %1",
	"Update" => "Cập nhật",
   	"d/m/Y h:i a" => "",
),
);
   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
