<?PHP
if (!defined('SYSINFO')) exit;
if (isset($_REQUEST['ll'])) $lang = strip_tags($_REQUEST['ll']);
else $lang = substr($_SERVER["HTTP_ACCEPT_LANGUAGE"], 0, 2);

$llang = "english";
$log_org = "be organized";
$log_org2 = "Calendar, Agenda, RSS Reader, Bookmarks...";
$log_prod = "be productive";
$log_prod2 = "Word Processor, Messaging System, Geolocation...";
$log_entr = "be entertained";
$log_entr2 = "Music and Video Player, Photo Galleries, Games...";
$log_conn = "be connected";
$log_conn2 = "Chat, Social Bookmarking, Public Board...";
$log_Username = "Username";
$log_Password = "Password";
$log_Language = "Language";
$log_create = "create a new account";
$log_Email = "E-mail";
$log_text1 = "Welcome to";
$log_text2 = "where you can create and use your own eyeOS Virtual Desktop. To find out more about eyeOS join our community by visiting the main <a href='http://eyeos.org' target='_blank'>eyeOS website</a>.";
$log_text3 = "With";
$log_text4 = "all your data is available where ever you have Internet access and a standards compliant browser.<p></p>You don`t know eyeOS? - Use the real help for eyeOS : <a href='system/en/index.html' target='_blank'>eyeOS - help</a>";
$log_butcreate = "create";
$log_butsignin = "sign in";
$mobile_v = "Mobile version";
$version = "<a href='http://eyeos.org'>eyeOS</a> with <a href='http://tms-od.de/eyeos/homepage/update-pack-en.html'>Update-Pack</a>";

switch ($lang) {
case "ar" :
	$llang = "arabic";
break;
case "ms" :
	$llang = "bahasa melayu";
break;
case "bn" :
	$llang = "bangla";
	$log_org = "সংগঠিত হও";
	$log_org2 = "দিনপন্জী, এজেন্ডা, RSS পাঠক, বুকমার্ক...";
	$log_prod = "উৎপাদনশীল হও";
	$log_prod2 = "ওয়ার্ডপ্রসেসিং, মেসেজিং সিস্টেম, Geolocation...";
	$log_entr = "আমোদিত হএ";
	$log_entr2 = "সঙ্গীত এবং ভিডিও প্লেয়ার,ফটো গ্যালারী, গেমস...";
	$log_conn = "সংযুক্ত হও";
	$log_conn2 = "আড্ডা, সামাজিক Bookmarking, উন্মুক্ত বোর্ড...";
	$log_Username = "ব্যাবহারকারী";
	$log_Password = "পাসওয়ার্ড";
	$log_Language = "ভাষা";
	$log_create = "নতুন একাউন্ট তৈরী কর";
	$log_Email = "ই-মেইল";
	$log_text1 = "এ স্বাগতম";
	$log_text2 = "যেখানে আপনি আপনার নিজস্ব eyeOS ভার্চুয়াল ডেষ্কটপ তৈরী এবং ব্যাবহার করতে পারবেন । আরও জানতে আমাদের গোষ্ঠীতে যোগদিন এবং ভিজিট করুন <a href='http://eyeos.org' target='_blank'>eyeOS ওয়েবসাইট</a>.";
	$log_text3 = "এর সাহায্যে ";
	$log_text4 = "আপনার সমস্ত ডেটা সবসময় পাচ্ছেন শুধুমাত্র একটি standard ব্রাউজার এবং ইন্টারনেট সংযোগ থাকলেই।";
	$log_butcreate = "তৈরী কর";
	$log_butsignin = "সাইন-ইন";
break;
case "pt_BR" :
	$llang = "brasileiro/português";
    $log_org = "organize-se";
    $log_org2 = "Calendário, Agenda, Leitor RSS, Favoritos...";
    $log_prod = "seja produtivo";
    $log_prod2 = "Editor de Texto, Sistema de Mensagens, Geolocalização...";
    $log_entr = "divirta-se";
    $log_entr2 = "Tocadores de Música e Vídeo, Galeria de Fotos, Jogos...";
    $log_conn = "conecte-se";
    $log_conn2 = "Chat, Favoritos Compartilhados, Quadro de Recados...";
    $log_Username = "Usuário";
    $log_Password = "Senha";
    $log_Language = "Idioma";
    $log_create = "Criar uma nova conta";
    $log_Email = "E-mail";
    $log_text1 = "Bem Vindo à";
    $log_text2 = "onde você pode criar e usar seu próprio desktop virtual eyeOS. Para saber mais sobre eyeOS junte-se à comunidade através do site principal do <a href='http://eyeos.org'>eyeOS</a>.";
    $log_text3 = "Com";
    $log_text4 = "todos os seus dados disponíveis onde quer que você tenha acesso à Internet e à um navegador convencional.";
    $log_butcreate = "criar";
    $log_butsignin = "entrar";
    $mobile_v = "Versão para dispositivos móveis";
break;
case "bg" :
	$llang = "bulgarian";
	$log_org = "бъди организиран";
	$log_org2 = "Календар, програма, RSS четец, отметки...";
	$log_prod = "бъдете продуктивни";
	$log_prod2 = "Текстов редактор, система за обмяна на съобщения, позициониране...";
	$log_entr = "забавлявайте се";
	$log_entr2 = "Плейъри за музика и видео, фото галерии, игри...";
	$log_conn = "бъдете свързани";
	$log_conn2 = "Чат, социални отметки, публични бюлетини...";
	$log_Username = "Потребител";
	$log_Password = "Парола";
	$log_Language = "Език";
	$log_create = "създаване на нов акаунт";
	$log_Email = "E-mail";
	$log_text1 = "Добре дошли в";
	$log_text2 = "където можете да създадете ваш собствен eyeOS виртуален работен плот. За да научите повече за eyeOS се присъединете към общността на основната <a href='http://eyeos.org' target='_blank'>eyeOS страница</a>.";
	$log_text3 = "С";
	$log_text4 = "всички данни са достъпни, там където имате Интернет връзка и съвместим със стандартите уеб браузър.";
	$log_butcreate = "създаване";
	$log_butsignin = "вход";
break;
case "ca" :
	$llang = "català";
	$log_org = "organitza't";
	$log_org2 = "Calendari, Agenda, Lector de RSS, Marcadors...";
	$log_prod = "sigues productiu";
	$log_prod2 = "Processador de Textes, Missatgeria, Geolocalizació...";
	$log_entr = "entretén-te";
	$log_entr2 = "Reproductor de música i vídeo, Galeríes, Jocs...";
	$log_conn = "connecta't";
	$log_conn2 = "Xat, Marcadors socials, Taulell Públic...";
	$log_Username = "Usuari";
	$log_Password = "Contrasenya";
	$log_Language = "Idioma";
	$log_create = "crea un nou compte";
	$log_Email = "E-mail";
	$log_text1 = "Benvingut a";
	$log_text2 = "on pots crear i utilitzar el teu propi Escriptori Virtual eyeOS. Per saber més sobre el projecte, vine a formar part de la comunitat visitant la <a href='http://eyeos.org' target='_blank'>web principal d'eyeOS</a>.";
	$log_text3 = "Amb";
	$log_text4 = "tots els teus arxius estan a tot arreu, allà on tu estiguis, sempre que hi hagi un navegador d'Internet.";
	$log_butcreate = "crear";
	$log_butsignin = "entrar";
break;
case "cs" :
	$llang = "český";
break;
case "zh" :
	$llang = "chinese";
    $log_org = "有組織力的";
    $log_org2 = "月曆，議程，RSS閱讀器，書籤...";
    $log_prod = "有生產力的";
    $log_prod2 = "文書處理器，傳訊系統，地圖資訊...";
    $log_entr = "有娛樂性的";
    $log_entr2 = "影音播放器，相簿，遊戲...";
    $log_conn = "有連結力的";
    $log_conn2 = "聊天，共同書籤，佈告欄...";
    $log_Username = "帳號";
    $log_Password = "密碼";
    $log_Language = "語言";
    $log_create = "創建新帳號";
    $log_Email = "電子郵件";
    $log_text1 = "歡迎來到";
    $log_text2 = "在此您可創建與使用你個人的eyeOS虛擬桌面，想更進一步的了解的話，請參加我們的社群：<a href='http://eyeos.org'>eyeOS website</a>.";
    $log_text3 = "藉由";
    $log_text4 = "只要您所在之處有著可上網的裝置和遵從網頁標準的網頁瀏覽器，就能隨時隨地存取自己所有的資料。";
    $log_butcreate = "創建";
    $log_butsignin = "登入";
    $mobile_v = "手持版本";
break;
case "hr" :
	$llang = "croatian";
break;
case "da" :
	$llang = "dansk";
break;
case "de" :
	$llang = "deutsch";
	$log_org = "sei organisiert";
	$log_org2 = "Kalender und Agenda, RSS Reader und Lesezeichen...";
	$log_prod = "sei produktiv";
	$log_prod2 = "Textverarbeitung, Nachrichtensystem...";
	$log_entr = "sei unterhalten";
	$log_entr2 = "Musik und Video Player, Foto-Gallerien und Spiele...";
	$log_conn = "sei verbunden";
	$log_conn2 = "Chat, gemeinsame Lesezeichen und öffentliches Forum...";
	$log_Username = "Benutzername";
	$log_Password = "Passwort";
	$log_Language = "Sprache";
	$log_create = "Neues Konto";
	$log_Email = "E-Mail";
	$log_text1 = "Willkommen zu";
	$log_text2 = "hier können Sie Ihren persönlichen eyeOS-Desktop einrichten und verwalten. Um mehr über eyeOS zu erfahren, besuchen Sie einfach die <a href='http://eyeos.de.md' target='_blank'>eyeOS-Webseite</a>.";
	$log_text3 = "Mit";
	$log_text4 = "sind Ihre Daten überall und jederzeit aus dem Internet mit einem der gängigen Standard-Browser zu erreichen.<br /><br />Sie kennen eyeOS noch nicht? - Verwenden Sie unsere <a href='system/de/index.html' target='_blank'>eyeOS-Hilfe</a>!";
	$log_butcreate = "Erstellen";
	$log_butsignin = "Anmelden";
    $mobile_v = "Handy-Version";
    $version = "<a href='http://eyeos.de.md'>eyeOS</a> mit <a href='http://eyeos.tms-od.de/update-pack.html'>Update-Pack</a>";
break;
case "es" :
	$llang = "español";
	$log_org = "organízate";
	$log_org2 = "Calendario, Agenda, Lector de RSS, Favoritos...";
	$log_prod = "sé productivo";
	$log_prod2 = "Procesador de Textos, Mensajería, Geolocalización...";
	$log_entr = "entretente";
	$log_entr2 = "Reproductor de música y video, Galerías, Juegos...";
	$log_conn = "conéctate";
	$log_conn2 = "Chat, Marcadores sociales, Tablón Público...";
	$log_Username = "Usuario";
	$log_Password = "Contraseña";
	$log_Language = "Idioma";
	$log_create = "crea una nueva cuenta";
	$log_Email = "E-mail";
	$log_text1 = "Bienvenido a";
	$log_text2 = "donde puedes crear y usar tu propio Escritorio Virtual eyeOS. Para saber más sobre eyeOS, ven a formar parte de la comunidad visitando la <a href='http://eyeos.org' target='_blank'>web principal de eyeOS</a>.";
	$log_text3 = "Con";
	$log_text4 = "todos tus archivos están en todos lados, allí donde estés, siempre que haya un navegador de Internet.";
	$log_butcreate = "crear";
	$log_butsignin = "entrar";
break;
case "eu" :
	$llang = "euskara";
break;
case "fr" :
	$llang = "français";
	$log_org = "Soyez organisé";
	$log_org2 = "Calendrier, Agenda, Lecteur RSS, Favoris...";
	$log_prod = "Soyez productif";
	$log_prod2 = "Traitement de texte, Messagerie, Geolocalisation...";
	$log_entr = "Divertissez-vous";
	$log_entr2 = "Lecteur de musique et vidéo, Albums Photos, Jeux...";
	$log_conn = "Soyez connecté";
	$log_conn2 = "Chat, Réseau social, Forums publics...";
	$log_Username = "Nom d'utilisateur";
	$log_Password = "Mot de passe";
	$log_Language = "Langue";
	$log_create = "créer un nouveau compte";
	$log_Email = "E-mail";
	$log_text1 = "Bienvenue à";
	$log_text2 = "Où vous pouvez créer et utiliser votre propre bureau virtuel EyeOS. Pour en savoir plus sur EyeOS, joignez notre communauté en visitant le <a href='http://eyeos.org' target='_blank'>site web de EyeOS</a>.";
	$log_text3 = "Avec";
	$log_text4 = "toutes vos données sont accessibles où que vous soyez avec une connexion internet et un navigateur compatible avec les standards.";
	$log_butcreate = "Créer";
	$log_butsignin = "identifier";
break;
case "gl" :
	$llang = "galego";
break;
case "el" :
	$llang = "greek";
    $log_org = "Οργάνωση";
    $log_org2 = "Ημερολογίο, Ατζέντα, Αναγνώστης RSS, Σελιδοδείκτες...";
    $log_prod = "Παραγωγικότητα";
    $log_prod2 = "Επεξεργαστής ΚειμένουWord, Σύστημα Μηνυμάτων, Γεοτοποθέτηση...";
    $log_entr = "Διασκέδαση";
    $log_entr2 = "Αναπαραγωγή Μουσικής και Βίντεο, Φωτογραφικά Άλμπουμ, Παιχνίδια...";
    $log_conn = "Συνδεσιμότητα";
    $log_conn2 = "Chat/Συνομιλίες, Δημοσίευση Σελιδοδεικτών, Public Board...";
    $log_Username = "Όνομα Χρήστη";
    $log_Password = "Κωδικός";
    $log_Language = "Γλώσσα";
    $log_create = "Δημιουργία νέου λογαριασμού";
    $log_Email = "E-mail";
    $log_text1 = "Καλωσήλθατε";
    $log_text2 = "που μπορείτε να δημιουργήσετε και να χρησιμοποιήσετε το δικό σας προσωπικό eyeOS εικονικό περιβάλλον εργασίας. Για περισσότερες πληροφορίες σχετικά με το eyeOS επισκεφθείτε την κοινότητα χρηστών του στον <a href='http://eyeos.org'>ιστοχώρο του eyeOS</a>.";
    $log_text3 = "Με";
    $log_text4 = "όλα τα δεδομένα σας είναι διαθέσιμα οπουδήποτε έχετε πρόσβαση στο Διαδίκτυο και έναν από τους γνωστούς περιηγητές.";
    $log_butcreate = "Δημιουργία";
    $log_butsignin = "Σύνδεση";
break;
case "it" :
	$llang = "italiano";
	$log_org = "essere organizzati";
	$log_org2 = "Calendario, Agenda, Lettore RSS, Segnalibri...";
	$log_prod = "essere produttivi";
	$log_prod2 = "Elaboratore di Testi, Messaggeria, Geolocalizzazione...";
	$log_entr = "divertirsi";
	$log_entr2 = "Riproduttore di Musica e Video, Gallerie Fotografiche, Giochi...";
	$log_conn = "essere connessi";
	$log_conn2 = "Chat, Segnalibri Sociali, Lavagna Pubblica...";
	$log_Username = "Nome Utente";
	$log_Password = "Password";
	$log_Language = "Lingua";
	$log_create = "crea un nuovo account";
	$log_Email = "E-mail";
	$log_text1 = "Benvenuti in";
	$log_text2 = "dove puoi creare e usare il tuo eyeOS Virtual Desktop. Per maggiori informazioni su eyeOS iscriviti alla nostra community sul <a href='http://eyeos.org'>sito ufficiale di eyeOS</a>.";
	$log_text3 = "Con";
	$log_text4 = "tutti i tuoi dati sono disponibili ovunque tu abbia un accesso ad internet ed un browser con i requisiti adatti.";
	$log_butcreate = "crea";
	$log_butsignin = "entra";
break;
case "ja" :
	$llang = "japanese";
break;
case "ko" :
	$llang = "korean";
break;
case "hu" :
	$llang = "magyar";
break;
case "nl" :
	$llang = "nederlands";
    $log_org = "georganiseerd";
    $log_org2 = "Kalender, agenda, RSS lezer, Bladwijzers, ...";
    $log_prod = "productief";
    $log_prod2 = "Tekstverwerker, berichten sturen, locaties opzoeken, ...";
    $log_entr = "entertainment";
    $log_entr2 = "Media speler, foto gallerijen, spelletjes, ...";
    $log_conn = "in contact blijven";
    $log_conn2 = "Chaten, sociale bladwijzers, publiekelijk forum, ...";
    $log_Username = "Gebruikersnaam";
    $log_Password = "Wachtwoord";
    $log_Language = "Taal";
    $log_create = "nieuw account";
    $log_Email = "E-mail";
    $log_text1 = "Welkom bij";
    $log_text2 = "waar je je eigen eyeOS Virtual Desktop kunt maken en gebruiken. Bezoek om meer over eyeOS te ontdekken de <a href='http://eyeos.org'>eyeOS website</a>.";
    $log_text3 = "Met";
    $log_text4 = "zijn al je bestanden overal waar je internet en een standaarden-respecterende browser hebt beschikbaar.";
    $log_butcreate = "aanmaken";
    $log_butsignin = "aanmelden";
break;
case "no" :
	$llang = "norsk";
break;
case "ir" :
	$llang = "persian";
	$log_org = "سازمان یافته شوید";
	$log_org2 = "تقویم ، برنامه ریزی ، خبر خوان ، سایت های برگزیده ، ...";
	$log_prod = "پر بار شوید";
	$log_prod2 = "پردازش کلمات ، سیستم پیام رسان ، موقعیت جغرافیایی ، ...";
	$log_entr = "سرگرم شوید";
	$log_entr2 = "پخش کننده موسیقی و فیلم ، مجموعه تصویر ، بازی ها ، ...";
	$log_conn = "متصل شوید";
	$log_conn2 = "گفتگو ، نشانه گذاری گروهی ، تابلوی عمومی ، ... ";
	$log_Username = "نام کاربری";
	$log_Password = "کلمه عبور";
	$log_Language = "زبان";
	$log_create = "ایجاد حساب جدید";
	$log_Email = "ایمیل";
	$log_text1 = "خوش آمدید به";
	$log_text2 = "جایی که میتوانید میزکار مجازی خود را بسازید و استفاده کنید. برای اطلاعات بیشتر درباره این برنامه عضو انجمن ما شوید برای این کار به <a href='http://eyeos.org' target='_blank'>eyeOS سایت</a> مراجعه کنید";
	$log_text3 = "با";
	$log_text4 = "تمام اطلاعات شما هر جایی که یک خط اینترنت و یک مرورگر آماده دارید در دسترس شما است.";
	$log_butcreate = "ایجاد";
	$log_butsignin = "ورود";
break;
case "pl" :
	$llang = "polski";
break;
case "pt" :
	$llang = "português";
	$log_org = "mantém-te organizado";
	$log_org2 = "Calendario, Agenda, Leitor de RSS, Favoritos...";
	$log_prod = "sê productivo";
	$log_prod2 = "Processador de Textos, Sistema de mensagens, Geolocalizaç�o...";
	$log_entr = "entretente";
	$log_entr2 = "Leitor de música e video, Galerias de Fotografias, Jogos...";
	$log_conn = "mantém-te conectado";
	$log_conn2 = "Chat, Apontadores sociais, Quadro P�blico...";
	$log_Username = "Utilizador";
	$log_Password = "Palavra-chave";
	$log_Language = "Idioma";
	$log_create = "criar uma nova conta";
	$log_Email = "E-mail";
	$log_text1 = "Bemvindo a";
	$log_text2 = "onde podes criar e usar o teu proprio Escritorio Virtual eyeOS. Para saber mais sobre eyeOS, vem-te informar através da comunidade visitando o <a href='http://eyeos.org'> site oficial de eyeOS</a>.";
	$log_text3 = "Com";
	$log_text4 = "todos os teus dados estarão dispon�veis, onde quer que estejas, desde que tenhas acesso a um navegador de Internet.";
	$log_butcreate = "criar";
	$log_butsignin = "entrar";
break;
case "ro" :
	$llang = "românesc";
break;
case "ru" :
	$llang = "russian";
    $log_org = "будь организован";
    $log_org2 = "Календарь, Заметки, RSS, Закладки...";
    $log_prod = "будь продуктивным";
    $log_prod2 = "Текстовый редактор, сообщения, карты...";
    $log_entr = "развлекись";
    $log_entr2 = "Музыка и видео, Фото, Игры...";
    $log_conn = "будь на связи";
    $log_conn2 = "Чат, социальные закладки, Доска Объявлений...";
    $log_Username = "Пользователь";
    $log_Password = "Пароль";
    $log_Language = "Язык";
    $log_create = "создать аккаунт";
    $log_Email = "E-mail";
    $log_text1 = "Добро пожаловать на";
    $log_text2 = "где вы можете создать и тспользовать ваш собственный кабинет eyeOS. Чтобы узнать побольше об этой системе посетите <a href='http://eyeos.org'>вебсайт eyeOS</a>.";
    $log_text3 = "С помощью";
    $log_text4 = "любые ваши данные доступны через интернет где бы вы ни находились через любой браузер.";
    $log_butcreate = "создать";
    $log_butsignin = "войти";
break;
case "sk" :
	$llang = "slovenský";
	$log_org = "ostati organiziran";
	$log_org2 = "Calendar, Agenda, RSS Reader, Bookmarks...";
	$log_prod = "ostati produktiven";
	$log_prod2 = "urejevalnik besedil, sistem obvescanja, Geolocation...";
	$log_entr = "ostali v zabavi";
	$log_entr2 = "predvajalniki glasbe in videa, foto galerije, igre...";
	$log_conn = "ostati povezan";
	$log_conn2 = "Chat, Social Bookmarking, Public Board...";
	$log_Username = "Uporabnisko ime";
	$log_Password = "Geslo";
	$log_Language = "Jezik";
	$log_create = "ustvarite nov racun";
	$log_Email = "E-mail";
	$log_text1 = "Dobrodosli v ";
	$log_text2 = "kjer si lahko ustvarite svojo navidezno eyeOS namizje. Za vec informacij o eyeOS, se prikljucite nasi skupini z obiskom glavne strani <a href='http://eyeos.org' target='_blank'>eyeOS-a</a>.";
	$log_text3 = "Z";
	$log_text4 = "so vsi vasi podatki dostopni povsod, kjer imate dostop do interneta s standardnim brskalnikom.";
	$log_butcreate = "ustvari";
	$log_butsignin = "prijava";
break;
case "fi" :
	$llang = "suomalainen";
	$log_org = "Ajankäyttö";
	$log_org2 = "Kalenteri, työjärjestys, RSS lukija, kirjanmerkit...";
	$log_prod = "Viestintä";
	$log_prod2 = "tekstinhallinta, internet viestintä, sijainti...";
	$log_entr = "Ajanviete";
	$log_entr2 = "Musiikki- ja videosoitin, valokuvakansiot, pelejä...";
	$log_conn = "Verkostoidu";
	$log_conn2 = "Neuvottele verkossa, yhteiset kirjanmerkit, ilmoitustaulu...";
	$log_Username = "Käyttäjänimi";
	$log_Password = "Salasana";
	$log_Language = "Valitse kieli";
	$log_create = "Luo uusi tili...";
	$log_Email = "Sähköposti";
	$log_text1 = "Tervetuloa";
	$log_text2 = "jossa voit käyttää omaa virtuaalista työpöytää. Opi enemmän liittymllä yhteisöömme. Käy  <a href='http://eyeos.org' target='_blank'>eyeOS verkkosivustolla</a>.";
	$log_text3 = "Ota käyttöön";
	$log_text4 = ", niin tarvisemasi tieto on käytössä siellä, missä pääset Internet verkkoon ja käytät standardin mukaista selainta.";
	$log_butcreate = "lähetä";
	$log_butsignin = "kirjaudu";
break;
case "sv" :
	$llang = "svensk";
    $log_org = "bli organiserad";
    $log_org2 = "Kalender, Agenda, RSS läsare, Bokmärken...";
    $log_prod = "bli produktiv";
    $log_prod2 = "Ordbehandlare, Meddelandesystem, Kartor...";
    $log_entr = "bli underhållen";
    $log_entr2 = "Musik och Video spelare, Foto gallerier, Spel...";
    $log_conn = "bli ihopkopplad";
    $log_conn2 = "Chat, Social bokmärkning, Allmän anslagstavla...";
    $log_Username = "Användarnamn";
    $log_Password = "Lösenord";
    $log_Language = "Språk";
    $log_create = "skapa ett nytt användarkonto";
    $log_Email = "E-postadress";
    $log_text1 = "Välkommen till";
    $log_text2 = "där du kan skapa och använda ditt egna eyeOS Virtuella Skrivbord. Om du vill veta mera om eyeOS, gå med i vår community genom att besöka huvudsidan, <a href='http://eyeos.org'>eyeOS hemsida</a>.";
    $log_text3 = "Med";
    $log_text4 = "finns all din data tillgänglig bara du har tillgång till Internet via en standard browser.";
    $log_butcreate = "skapa";
    $log_butsignin = "logga in";
    $mobile_v = "Mobil version";
break;
case "th" :
	$llang = "thai";
    $log_org = "คือการจัดการ";
    $log_org2 = "ปฏทิน, การบันทึกกำหนดการ, ระบบอ่าน RSS , บันทึกเว็บสำคัญ...";
    $log_prod = "คือการสร้าง";
    $log_prod2 = "โปรแกรมพิมพ์งาน, ระบบส่งข้อความ, ระบบแผนที่...";
    $log_entr = "คือความบันเทิง";
    $log_entr2 = "เพลง และโปรแกรมเล่นวิดีโอ, แกลเลอรี่ภาพ, เกมส์...";
    $log_conn = "คือการเชื่อมถึง";
    $log_conn2 = "โปรแกรมแชท, เว็บสำคัญส่วนรวม, บอร์ดสาธารณะ...";
    $log_Username = "ชื่อผู้ใช้งาน";
    $log_Password = "รหัสผ่าน";
    $log_Language = "ภาษา";
    $log_create = "สร้างบัญชีผู้ใช้งานใหม่";
    $log_Email = "อีเมล";
    $log_text1 = "ยินดีต้อนรับ";
    $log_text2 = "ที่ซึ่งคุณสามารถสร้างและใช้ eyeOS Virtual Desktop. เพื่อรายละเอียดเพิ่มเติมเกี่ยวกับ eyeOS สามารถเข้าร่วมชุมชนโดยการเข้าไปเว็บ <a href='http://eyeos.org'>eyeOS </a>.";
    $log_text3 = "ซึ่ง";
    $log_text4 = "ข้อมูลของคุณทั้งหมดสามารถเข้าถึงได้ ในทุกๆที่ ที่สามารถใช้งานอินเตอร์เน็ตได้ และมีเว็บบราวเซอร์มาตรฐาน";
    $log_butcreate = "สร้าง";
    $log_butsignin = "เข้าระบบ";
break;
case "tr" :
	$llang = "türk";
    $log_org = "düzenleyin";
    $log_org2 = "Takvim, Ajanda, RSS Okuyucu, Yerimleri...";
    $log_prod = "olusturun";
    $log_prod2 = "Kelime Islemci, Mesajlasma, Geolocation...";
    $log_entr = "eglenin";
    $log_entr2 = "Müzik ve Video Oynatici, Resim Galerisi, Oyunlar...";
    $log_conn = "baglanin";
    $log_conn2 = "Sohbet, Toplumsal Yerimleri, Mesaj Tahtasi...";
    $log_Username = "Kullanici Adi";
    $log_Password = "Sifre";
    $log_Language = "Dil";
    $log_create = "yeni hesap olustur";
    $log_Email = "E-posta";
    $log_text1 = "Hosgeldiniz";
    $log_text2 = "Kendi eyeOS Sanal Masaüstünüzü olusturabilir ve kullanabilirsiniz. Daha fazla bilgi için <a href='http://eyeos.org'>burayi</a>tiklayin.";
    $log_text3 = "Ve";
    $log_text4 = " ile bütün dosyalariniza sadece internet baglantisi ve uyumlu web browser'la ulasabileceksiniz.";
    $log_butcreate = "olustur";
    $log_butsignin = "giris";
break;
case "ua" :
	$llang = "ukrainian";
    $log_org = "стань організованим";
    $log_org2 = "Календар, Записник, Переглядач RSS, Обране...";
    $log_prod = "стань продуктивним";
    $log_prod2 = "Редактор тексту, Повідомлення...";
    $log_entr = "будь веселим";
    $log_entr2 = "Програвач музики та відео, Фотогалереї, Ігри...";
    $log_conn = "будь на зв'язку";
    $log_conn2 = "Спілкування, Обране, Дошка Обговорення...";
    $log_Username = "Користувач";
    $log_Password = "Пароль";
    $log_Language = "Мова";
    $log_create = "створи нового користувача";
    $log_Email = "Адреса електронної пошти";
    $log_text1 = "Раді вітати у";
    $log_text2 = "де ти можеш створити та користуватися власним робочим столом eyeOS. Для того, щоб дізнатися більше, відвідай сторінку <a href='http://www.eyeos.org'>eyeOS</a>.";
    $log_text3 = "За допомою";
    $log_text4 = "всі твої дані належать тобі там, де в тебе є доступ до мережі та звичайнин браузер.";
    $log_butcreate = "створити";
    $log_butsignin = "увійти";
break;
case "vi" :
	$llang = "việt";
break;
default:
	$llang = "english";
	$log_org = "be organized";
	$log_org2 = "Calendar, Agenda, RSS Reader, Bookmarks...";
	$log_prod = "be productive";
	$log_prod2 = "Word Processor, Messaging System, Geolocation...";
	$log_entr = "be entertained";
	$log_entr2 = "Music and Video Player, Photo Galleries, Games...";
	$log_conn = "be connected";
	$log_conn2 = "Chat, Social Bookmarking, Public Board...";
	$log_Username = "Username";
	$log_Password = "Password";
	$log_Language = "Language";
	$log_create = "create a new account";
	$log_Email = "E-mail";
	$log_text1 = "Welcome to";
	$log_text2 = "where you can create and use your own eyeOS Virtual Desktop. To find out more about eyeOS join our community by visiting the main <a href='http://eyeos.org' target='_blank'>eyeOS website</a>.";
	$log_text3 = "With";
	$log_text4 = "all your data is available where ever you have Internet access and a standards compliant browser.<br /><br />You don`t know eyeOS? - Use our <a href='system/en/index.html' target='_blank'>eyeOS help</a>!";
	$log_butcreate = "create";
	$log_butsignin = "sign in";
	$mobile_v = "Mobile version";
	$version = "<a href='http://eyeos.org'>eyeOS</a> with <a href='http://tms-od.de/eyeos/homepage/update-pack-en.html'>Update-Pack</a>";
break;
}
?>