<?PHP
/* Application language file 
   */
   
$AppLanguages = array (
'english' => array (), // 23 strings
'arabic' => array ( // 8 strings
	"Go" => "إضغط",
	"Search" => "بحث",
	"File will be permanently deleted. Continue?" => "سيتم مسح الملف كليا. أتريد الإستمرار؟",
	"Save this page" => "حفظ هذه الصفحة",
	"Title" => "العنوان",
	"Private" => "للخاصة",
	"Public" => "للعامة",
	"There are no bookmarks" => "لا يوجد أي تأشيرات",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'bahasa melayu' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'bangla' => array ( // 8 strings
	"Go" => "যাও",
	"Search" => "অনুসন্ধান",
	"File will be permanently deleted. Continue?" => "ফাইল চিরতের মুছে ফেলা হবে । এগিয়ে যেতে চান?",
	"Save this page" => "এই পাতা সংরক্ষণ কর",
	"Title" => "শিরোনাম",
	"Private" => "ব্যাক্তিগত",
	"Public" => "উন্মুক্ত",
	"There are no bookmarks" => "কোন বুকমার্ক নেই",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'brasileiro/português' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'bulgarian' => array ( // 1 strings
	"Go" => "Отиди",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'català' => array ( // 3 strings
	"Go" => "Anar",
	"Search" => "Cercar",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "No hi ha marcadors",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'český' => array ( // 1 strings
	"Go" => "Jdi",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'chinese' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'croatian' => array ( // 1 strings
	"Go" => "Idi",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'dansk' => array ( // 1 strings
	"Go" => "Gå",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'deutsch' => array ( // 23 strings
	"Go" => "Start",
	"Search" => "Suchen",
	"File will be permanently deleted. Continue?" => "Soll die Datei wirklich gelöscht werden?",
	"Save this page" => "Seite als Lesezeichen",
	"Title" => "Titel",
	"Private" => "persönlich",
	"Public" => "öffentlich",
	"There are no bookmarks" => "Keine Lesezeichen vorhanden",
	"Google" => "Google",
	"A9" => "A9",
	"Amazon" => "Amazon",
	"Ask" => "Ask",
	"eBay" => "eBay",
	"MSN" => "MSN",
	"Yahoo" => "Yahoo",
	"http://www.google.com/search?q=%0" => "http://www.google.de/search?q=%0",
	"http://a9.com/%0" => "http://a9.com/%0",
	"http://www.ask.com/web?q=%0" => "http://de.ask.com/web?q=%0",
	"http://search.yahoo.com/search?p=%0" => "http://search.yahoo.de/search?p=%0",
	"http://search.msn.com/results.aspx?q=%0" => "http://search.msn.de/results.aspx?q=%0",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "http://www.amazon.de/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0",
	"http://search.ebay.com/%0" => "http://search.ebay.de/%0",
	"Set the startpage of eyeNav" => "Startseite von eyeNav",
),
'español' => array ( // 3 strings
	"Go" => "Ir",
	"Search" => "Buscar",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "No hay favoritos",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "http://www.google.es/search?q=%0",
	"http://a9.com/%0" => "http://a9.com/%0",
	"http://www.ask.com/web?q=%0" => "http://es.ask.com/web?q=%0",
	"http://search.yahoo.com/search?p=%0" => "http://search.yahoo.es/search?p=%0",
	"http://search.msn.com/results.aspx?q=%0" => "http://search.msn.es/results.aspx?q=%0",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0",
	"http://search.ebay.com/%0" => "http://search.ebay.es/%0",
	"Set the startpage of eyeNav" => "",
),
'euskara' => array ( // 1 strings
	"Go" => "Joan",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'français' => array ( // 8 strings
	"Go" => "OK",
	"Search" => "Rechercher",
	"File will be permanently deleted. Continue?" => "Le fichier va être effacé définitivement. Continuer?",
	"Save this page" => "Enregistrer cette page",
	"Title" => "Titre",
	"Private" => "Privé",
	"Public" => "Publique",
	"There are no bookmarks" => "Il n'y a pas de marque-pages",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "http://www.google.fr/search?q=%0",
	"http://a9.com/%0" => "http://a9.com/%0",
	"http://www.ask.com/web?q=%0" => "http://fr.ask.com/web?q=%0",
	"http://search.yahoo.com/search?p=%0" => "http://search.yahoo.fr/search?p=%0",
	"http://search.msn.com/results.aspx?q=%0" => "http://search.msn.fr/results.aspx?q=%0",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "http://www.amazon.fr/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0",
	"http://search.ebay.com/%0" => "http://search.ebay.fr/%0",
	"Set the startpage of eyeNav" => "",
),
'galego' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'greek' => array ( // 8 strings
	"Go" => "Πάμε",
	"Search" => "Αναζήτηση",
	"File will be permanently deleted. Continue?" => "Το αρχείο θα διαγραφεί οριστικά. Να συνεχίσω?",
	"Save this page" => "Αποθήκευση της σελίδας",
	"Title" => "Τίτλος",
	"Private" => "Προσωπικά",
	"Public" => "Δημόσιο",
	"There are no bookmarks" => "Δεν υπάρχουν σελιδοδείκτες",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'italiano' => array ( // 1 strings
	"Go" => "Vai",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'japanese' => array ( // 1 strings
	"Go" => "進む",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'korean' => array ( // 1 strings
	"Go" => "가기",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'magyar' => array ( // 1 strings
	"Go" => "Pergi",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'nederlands' => array ( // 8 strings
	"Go" => "Ga",
	"Search" => "Zoeken",
	"File will be permanently deleted. Continue?" => "Het bestand zal voorgoed verwijderd worden. Doorgaan?",
	"Save this page" => "Pagina opslaan",
	"Title" => "Titel",
	"Private" => "Prive",
	"Public" => "Openbaar",
	"There are no bookmarks" => "Er zijn geen bladwijzers",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'norsk' => array ( // 1 strings
	"Go" => "Gå",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'polski' => array ( // 8 strings
	"Go" => "Idź",
	"Search" => "Szukaj",
	"File will be permanently deleted. Continue?" => "Plik zostanie usunięty na stałe. kontynuować?",
	"Save this page" => "Zapisz tą stronę",
	"Title" => "Tytuł",
	"Private" => "Prywatne",
	"Public" => "Publiczne",
	"There are no bookmarks" => "Brak zakładek",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'português' => array ( // 8 strings
	"Go" => "Ir",
	"Search" => "Pesquisar",
	"File will be permanently deleted. Continue?" => "O documento irá ser definitivamente eliminado. Continuar?",
	"Save this page" => "Guardar esta página",
	"Title" => "Titulo",
	"Private" => "Privado",
	"Public" => "Público",
	"There are no bookmarks" => "Não existem favoritos",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'românesc' => array ( // 1 strings
	"Go" => "Dute",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'russian' => array ( // 1 strings
	"Go" => "Переход",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'slovenský' => array ( // 1 strings
	"Go" => "Prejsť",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'suomalainen' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'svensk' => array ( // 0 strings
	"Go" => "",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'türk' => array ( // 8 strings
	"Go" => "",
	"Search" => "Ara",
	"File will be permanently deleted. Continue?" => "Dosya geri getirilemeyecek şekilde silinecektir. Devam?",
	"Save this page" => "Bu sayfayı kaydet",
	"Title" => "Başlık",
	"Private" => "Özel",
	"Public" => "Genel",
	"There are no bookmarks" => "Yerimi mevcut değil",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'ukrainian' => array ( // 8 strings
	"Go" => "Вперед!",
	"Search" => "Шукати",
	"File will be permanently deleted. Continue?" => "Документ буде видалено. Продовжити?",
	"Save this page" => "Зберегти сторінку",
	"Title" => "Назва",
	"Private" => "Особисто",
	"Public" => "Публічно",
	"There are no bookmarks" => "Обране відсутнє",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
'việt' => array ( // 1 strings
	"Go" => "Idi",
	"Search" => "",
	"File will be permanently deleted. Continue?" => "",
	"Save this page" => "",
	"Title" => "",
	"Private" => "",
	"Public" => "",
	"There are no bookmarks" => "",
	"Google" => "",
	"A9" => "",
	"Amazon" => "",
	"Ask" => "",
	"eBay" => "",
	"MSN" => "",
	"Yahoo" => "",
	"http://www.google.com/search?q=%0" => "",
	"http://a9.com/%0" => "",
	"http://www.ask.com/web?q=%0" => "",
	"http://search.yahoo.com/search?p=%0" => "",
	"http://search.msn.com/results.aspx?q=%0" => "",
	"http://www.amazon.com/gp/search/ref=br_ss_hs/102-6134268-4237749?search-alias=aps&keywords=%0" => "",
	"http://search.ebay.com/%0" => "",
	"Set the startpage of eyeNav" => "",
),
);
   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
