<?PHP
/* Application language file 
   */
   
$AppLanguages = array (
'catalan' => array (
	'Install' => "Instal·lar",
	'Application successfully installed' => "Aplicació instalada amb èxit",
	'Error: The file you uploaded is not an eyeOS application package' => "Error: L'arxiu que intentes instal·lar no sembla ser un paquet vàlid",
	'File already exists' => "La aplicació ja existeix",
	'Application deleted successfully' => "Aplicació esborrada amb èxit",
	'The application will be permanently deleted. Continue?' => "La aplicació serà esborrada permanentment. Continuar?",
	'Install a new application' => "Instal·lar una nova aplicació",
	'Select application package' => "Seleccionar el paquet d'instal·lació",
	'[Auto-close : %0]' => "[Tancar automàticament : %0]",
	'Manage Apps' => "Gestionar aplicacions",
	'Install Apps' => "Instal·lar aplicacions",
	'Name' => "Nom",
	'Icon' => "Icona",
	'Auto' => "Auto",
	'Skin' => "Pell",
	'Groupware' => "Aplicacions de grup",
	'File Management' => "Gestió d'arxius",
	'Office' => "Oficina",
	'System' => "Sistema",
	'Games' => "Jocs",
	'Widgets' => "Widgets",
	'Other' => "Altres",
),
'spanish' => array (
	'Install' => "Instalar",
	'Application successfully installed' => "Aplicación instalada con éxito",
	'Error: The file you uploaded is not an eyeOS application package' => "Error: El archivo que intentas instalar no parece ser un paquete válido",
	'File already exists' => "La aplicación ya existe",
	'Application deleted successfully' => "Aplicación borrada con éxito",
	'The application will be permanently deleted. Continue?' => "La aplicación será borrada permanentemente. Continuar?",
	'Install a new application' => "Instalar una nueva aplicación",
	'Select application package' => "Seleccionar el paquete de instalación",
	'[Auto-close : %0]' => "[Cerrar automaticamente : %0]",
	'Manage Apps' => "Gestionar aplicaciones",
	'Install Apps' => "Instalar aplicaciones",
	'Name' => "Nombre",
	'Icon' => "Icono",
	'Auto' => "Auto",
	'Skin' => "Piel",
	'Update app configuration' => "Actualizar la configuración",
	'Groupware' => "Aplicaciones de grupo",
	'File Management' => "Gestión de archivos",
	'Office' => "Oficina",
	'System' => "Sistema",
	'Games' => "Juegos",
	'Widgets' => "Widgets",
	'Other' => "Otros",
),
'german' => array (
	'Install' => "Installieren",
	'Application successfully installed' => "Anwendung erfolgreich installiert",
	'Error: The file you uploaded is not an eyeOS application package' => "Fehler: Die hochgeladene Datei ist kein eyeOS-Anwendungs-Package",
	'File already exists' => "Datei existiert bereits",
	'Application deleted successfully' => "Anwendung erfolgreich gelöscht",
	'The application will be permanently deleted. Continue?' => "Die Anwendung wird unwiederruflich gelöscht. Trotzdem fortfahren?",
	'Install a new application' => "Neue Anwendung installieren",
	'Select application package' => "Anwendungs-Package auswählen",
),
'french' => array (
	'Install' => "Installer",
	'Application successfully installed' => "Application installé avec succes",
	'Error: The file you uploaded is not an eyeOS application package' => "Erreur: Le fichier téléversé n'est pas un paquet application eyeOS",
	'File already exists' => "Fichier déja existant",
	'Application deleted successfully' => "Application supprimé avec succes",
	'The application will be permanently deleted. Continue?' => "L'application sera supprimé de facon permanente. Continuer?",
	'Install a new application' => "Installer une nouvelle application",
	'Select application package' => "Choisir un paquet application",
	'[Auto-close : %0]' => "[Fermeture automatique: %0]",
	'Manage Apps' => "Gérer les Applications",
	'Install Apps' => "Installer des Applications",
	'Name' => "Nom",
	'Icon' => "Icon",
	'Auto' => "Auto",
	'Skin' => "Skin",
	'Update app configuration' => "Mettre à jour la configuration de l'application",
), 
'turkish' => array (
	'Install' => "Kur",
	'Application successfully installed' => "Program başarılı bir şekilde kuruldu",
	'Error: The file you uploaded is not an eyeOS application package' => "Hata: Yolladığınız dosya eyeOS için hazırlanan bir program paketi değil",
	'File already exists' => "Dosya zaten mevcut",
	'Application deleted successfully' => "Program başarıyla silindi",
	'The application will be permanently deleted. Continue?' => "Program geri getirilemeyecek şekilde silinecektir. Devam ?",
	'Install a new application' => "Yeni bir program kur",
	'Select application package' => "Program paketi seç",
),
'bulgarian' => array (
	'Install' => "Инсталация",
	'Application successfully installed' => "Приложението е инсталирано успешно",
	'Error: The file you uploaded is not an eyeOS application package' => "Грешка: Файлът, който качихте, не е eyeOS пакет с приложение",
	'File already exists' => "Файлът вече съществува",
	'Application deleted successfully' => "Приложението е изтрито успешно",
	'The application will be permanently deleted. Continue?' => "Приложението ще бъде изтрито. Сигурни ли сте?",
	'Install a new application' => "Инсталиране на ново приложение",
	'Select application package' => "Изберете пакет с приложение",
	'[Auto-close : %0]' => "[Автом. затваряне : %0]",
	'Manage Apps' => "Управление на приложенията",
	'Install Apps' => "Инсталиране на приложения",
	'Name' => "Име",
	'Icon' => "Икона",
	'Auto' => "Автом.",
	'Skin' => "Кожа",
	'Update app configuration' => "Обновяване на конфигурацията на приложението",
),
'polish' => array (
	'Install' => "Instaluj",
	'Application successfully installed' => "Aplikacja została zainstalowana",
	'Error: The file you uploaded is not an eyeOS application package' => "Błąd: Plik jaki wgrałeś , nie jest aplikacją eyeOS",
	'File already exists' => "Plik juz istnieje",
	'Application deleted successfully' => "Aplikacja została usunięta",
	'The application will be permanently deleted. Continue?' => "plikacja zostanie usunięta na stałe. Kontynuować?",
	'Install a new application' => "Instaluj nową aplikację",
	'Select application package' => "Wybierz paczkę z aplikacją",
	'[Auto-close : %0]' => "[Automatyczne zamykanie : %0]",
	'Manage Apps' => "Zarządzaj aplikacjami",
	'Install Apps' => "Instaluj aplikację",
	'Name' => "Nazwa",
	'Icon' => "Ikona",
	'Auto' => "Auto",
	'Skin' => "Skórka",
	'Update app configuration' => "Uaktualnij konfigurację aplikacji",
),
'portuguese' => array (
	'Install' => "Instalar",
	'Application successfully installed' => "Aplicativo instalado com sucesso",
	'Error: The file you uploaded is not an eyeOS application package' => "Erro: O documento que foi inserido não é um pacote de um aplicativo do eyeOS",
	'File already exists' => "O documento já existe",
	'Application deleted successfully' => "Aplicativo eliminado com sucesso",
	'The application will be permanently deleted. Continue?' => "O aplicativo será eliminado. Continuar?",
	'Install a new application' => "Instalar um aplicativo novo",
	'Select application package' => "Selecionar pacote de um aplicativo",
),
'swedish' => array (
	'Install' => "Installera",
	'Application successfully installed' => "Programmet installerades",
	'Error: The file you uploaded is not an eyeOS application package' => "Fel: filen du laddade upp är inte ett eyeOS-program",
	'File already exists' => "Filen finns redan",
	'Application deleted successfully' => "Programmet raderades",
	'The application will be permanently deleted. Continue?' => "Programmet kommer att raderas permanent. Vill du fortsätta?",
	'Install a new application' => "Installera ett nytt program",
	'Select application package' => "Välj programpaket",
),
'chinese' => array (
	'Install' => "安装",
	'Application successfully installed' => "程序安装完成",
	'Error: The file you uploaded is not an eyeOS application package' => "错误：你所上传的文件不是eyeOS应用程序包",
	'File already exists' => "文件已存在",
	'Application deleted successfully' => "程序删除成功",
	'The application will be permanently deleted. Continue?' => "程序将被永久删除，确定吗？",
	'Install a new application' => "安装新程序",
	'Select application package' => "选择新程序包",
),
'dutch' => array (
	'Install' => "Installeren",
	'Application successfully installed' => "Programma succesvol geinstalleerd",
	'Error: The file you uploaded is not an eyeOS application package' => "Fout: het ge-uploade bestand is geen eyeOS programma",
	'File already exists' => "Bestand bestaat al",
	'Application deleted successfully' => "Programma succesvol verwijderd",
	'The application will be permanently deleted. Continue?' => "Het programma wordt voorgoed verwijderd. Doorgaan?",
	'Install a new application' => "Nieuw programma installeren",
	'Select application package' => "Programma kiezen",
),
'hungarian' => array (
	'Install' => "Telepítés",
	'Application successfully installed' => "Az alkalmazás sikeresen telepítve",
	'Error: The file you uploaded is not an eyeOS application package' => "Hiba: A feltöltött fájl nem eyeOS csomag",
	'File already exists' => "A fájl már létezik",
	'Application deleted successfully' => "az alkalamazás sikeresen törölve",
	'The application will be permanently deleted. Continue?' => "Az alkalmazás véglegesen törölve lesz. Folytatja?",
	'Install a new application' => "Új alkalmazás telepítése",
	'Select application package' => "Válassz egy alkalmazás csomagot",
),
'italian' => array (
	'Install' => "Installa",
	'Application successfully installed' => "Applicazione installata",
	'Error: The file you uploaded is not an eyeOS application package' => "Errore: Il file caricato non è un'applicazione eyeOS",
	'File already exists' => "Il file esiste",
	'Application deleted successfully' => "Applicazione cancellata",
	'The application will be permanently deleted. Continue?' => "L'applicazione sarà cancellata. Continuo?",
	'Install a new application' => "Installa una nuova applicazione",
	'Select application package' => "Seleziona un'applicazione",
),
'russian' => array (
	'Install' => "Поставить",
	'Application successfully installed' => "Программа установлена",
	'Error: The file you uploaded is not an eyeOS application package' => "Это - не файл eyeOS",
	'File already exists' => "Такой файл уже есть",
	'Application deleted successfully' => "Приложение успешно удалено",
	'The application will be permanently deleted. Continue?' => "Программа будет удалена. Продолжить?",
	'Install a new application' => "Поставить новую программу",
	'Select application package' => "Выберите пакет",
),
'danish' => array (
	'Install' => "Installere",
	'Application successfully installed' => "Applikationen er installeret",
	'Error: The file you uploaded is not an eyeOS application package' => "Fejl: Filen du uploadede, er ikke en eyeOS applikation",
	'File already exists' => "Filen findes allerede",
	'Application deleted successfully' => "Applikation er blevet slettet",
	'The application will be permanently deleted. Continue?' => "Applikationen vil blive permanent slettet, forsæt ?",
	'Install a new application' => "Installere ny applicaktion",
	'Select application package' => "Vælg applikations pakke",
),
'finnish' => array (
	'Install' => "Asenna",
	'Application successfully installed' => "Sovellus asennettiin onnistuneesti",
	'Error: The file you uploaded is not an eyeOS application package' => "Lataamsi tiedosto ei ole eyeOS sovellustiedosto",
	'File already exists' => "Tiedosto on jo olemassa",
	'Application deleted successfully' => "Sovellus poitettiin onnistuneesti",
	'The application will be permanently deleted. Continue?' => "Sovellus poistetaan pysyvästi. Jatkatko?",
	'Install a new application' => "Asenna uusi sovellus",
	'Select application package' => "Valitse sovelluspaketti",
),
'romanian' => array (
	'Install' => "Instaleaza",
	'Application successfully installed' => 'Programul a fost instalat corect' ,
	'Error: The file you uploaded is not an eyeOS application package' => 'Eroare: Fisierul care l-ai uploadat nu este recunoscut de eyeOS' ,
	'File already exists' => "Fisierul deja exista",
	'Application deleted successfully' => 'Programul a fost stears corect' ,
	'The application will be permanently deleted. Continue?' => 'Programul va fi sters definitiv. Esti sigur ca vrei sa continui?' ,
	'Install a new application' => 'Instaleaza un program nou' ,
	'Select application package' => 'Alege programul',
	'[Auto-close : %0]' => "[Inchidere automata : %0]",
	'Manage Apps' => "Organizeaza programele",
	'Install Apps' => "Instaleaza programe",
	'Name' => "Nume",
	'Icon' => "Icon",
	'Auto' => "Auto",
	'Skin' => "Interfata",
	'Update app configuration' => "Actualizeaza programul",
),
);
   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
