<?PHP
/* Application language file 
   */
   
$AppLanguages = array (

'catalan' => array (
	'Note %0 succesfully saved' => 'Nota %0 desada amb èxit',	 //%0 is note title
	'Some fields were not completed' => "Alguns camps no han estat completats",	
	'Note %0 succesfully deleted' => "Nota %0 esborrada amb èxit",	//%0 is note title
	'Note %0 not exists' => "La nota %0 no existeix",	//%0 is note title
	'Private notes' => "Notes privades",	
	'There are no private notes' => "No hi ha notes privades",	
	'Public notes' => "Notes públiques",	
	'There are no public notes' => "No hi ha notes públiques",	
	'Editing note' => "Editant la nota",	
	'Last changed by %0 at %1' => "Últim canvi per %0 a %1",	//%0 is note author, %1 is the date
	'Title' => "Títol",	
	'Status' => "Estat",	
	'Public' => "Pública",
	'Private' => "Privada",
	'New note' => "Nova nota",
	'Open note' => "Obrir una nota",
	'Copy to Home as HTML file' => "Exportar a fitxer HTML",

),
'spanish' => array (
	'Note %0 succesfully saved' => 'Nota %0 guardada correctamente',	 //%0 is note title
	'Some fields were not completed' => 'Algunos campos no fueron completados',	
	'Note %0 succesfully deleted' => 'Nota %0 borrada correctamente',	//%0 is note title
	'Note %0 not exists' => 'Nota %0 inexistente',	//%0 is note title
	'Private notes' => 'Notas privadas',	
	'There are no private notes' => 'No hay notas privadas',	
	'Public notes' => 'Notas públicas',	
	'There are no public notes' => 'No hay notas públicas',		
	'Editing note' => 'Editando nota',	
	'Last changed by %0 at %1' => 'Última actualización por %0 el %1',	//%0 is note author, %1 is the date
	'Title' => 'Título',	
	'Status' => 'Estado',	
	'Public' => 'Público',
	'Private' => 'Privado',
	'New note' => 'Nueva nota',
	'Open note' => "Abrir una nota",
	'Copy to Home as HTML file' => "Exportar a fichero HTML",
),
'bulgarian' => array (
	'Note %0 succesfully saved' => 'Бележката %0 е записана успешно',	 //%0 is note title
	'Some fields were not completed' => "Някой полета не са попълнени",	
	'Note %0 succesfully deleted' => "Бележката %0 е изтрита успешно",	//%0 is note title
	'Note %0 not exists' => "Бележката %0 не съществува",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Файлът ще бъде изтрит! Искате ли да продължите?",	
	'Private notes' => "Лични бележки",	
	'There are no private notes' => "Няма лични бележки",	
	'Public notes' => "Публични бележки",	
	'There are no public notes' => "Няма публични бележки",	
	'Editing note' => "Редактиране на бележка",	
	'Last changed by %0 at %1' => "Последно променена от %0 на %1" ,	//%0 is note author, %1 is the date
	'Title' => "Заглавие",	
	'Status' => "Статус",	
	'Public' => "Публични",
	'Private' => "Лични",
	'New note' => "Нова бележка",
	'Copy to Home as HTML file' => "Копиране в Home като HTML дайл",
),
'polish' => array (
	'Note %0 succesfully saved' => 'Notatka',	 //%0 is note title
	'Some fields were not completed' => "Nie wszystkie pola zostały wypełnione",	
	'Note %0 succesfully deleted' => "Notatka %0 została usunięta",	//%0 is note title
	'Note %0 not exists' => "Notatka %0 nie istnieje",	//%0 is note title
	'Private notes' => "Prywatne notatki",	
	'There are no private notes' => "Brak prywatnych notatek",	
	'Public notes' => "Publiczne notatki",	
	'There are no public notes' => "Brak publicznych notatek",	
	'Editing note' => "Edytuj notatkę",	
	'Last changed by %0 at %1' => "Ostatnia zmiana dokonana przez %0 w dniu %1",	//%0 is note author, %1 is the date
	'Title' => "Tytuł",	
	'Status' => "Status",	
	'Public' => "Publiczna",
	'Private' => "Prywatna",
	'New note' => "Nowa notatka",
	'Copy to Home as HTML file' => "Kopiuj do Home jako plik HTML",
),
'french' => array (
	'Note %0 succesfully saved' => 'Note %0 sauvegardée avec succès',	 //%0 is note title
	'Some fields were not completed' => "Un ou plusieurs champs n'a (n'ont) pas été completé(s)",	
	'Note %0 succesfully deleted' => "Note %0 supprimée avec succès",	//%0 is note title
	'Note %0 not exists' => "Note %0 n'existe pas",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Le fichier va être effacé de manière permanente. Continuer?",	
	'Private notes' => "Notes privées",	
	'There are no private notes' => "Il n'y a pas de notes privées",	
	'Public notes' => "Notes publiques",	
	'There are no public notes' => "Il n'y a pas de notes publiques",	
	'Editing note' => "Editer note",	
	'Last changed by %0 at %1' => "Dernier changement par %0 à %1",	//%0 is note author, %1 is the date
	'Title' => "Titre",	
	'Status' => "Statut",	
	'Public' => "Publique",
	'Private' => "Privé",
	'New note' => "Nouvelle note",

),
'german' => array (
	'Note %0 succesfully saved' => "Notiz %0 erfolgreich gespeichert",	 //%0 is note title
	'Some fields were not completed' => "Einige Felder waren nicht ausgefüllt",	
	'Note %0 succesfully deleted' => "Notiz %0 erfolgreich gelöscht",	//%0 is note title
	'Note %0 not exists' => "Notiz %0 existiert nicht",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Die Datei wird unwiederruflich gelöscht. Trotzdem fortfahren?",	
	'Private notes' => "Private Notizen",	
	'There are no private notes' => "Keine privaten Notizen vorhanden",	
	'Public notes' => "Öffentliche Notizen",	
	'There are no public notes' => "Keine öffentlichen Notizen vorhanden",		
	'Editing note' => "Bearbeite Notiz",	
	'Last changed by %0 at %1' => "Zuletzt geändert von %0 am %1",	//%0 is note author, %1 is the date
	'Title' => "Titel",	
	'Status' => "Status",	
	'Public' => "Öffentlich",
	'Private' => "Privat",
	'New note' => "Neue Notiz",
),
'turkish' => array (
	'Note %0 succesfully saved' => '%0 başlıklı not başarıyla kaydedildi.',	 //%0 is note title
	'Some fields were not completed' => "Gerekli alanları boş bırakmayınız",	
	'Note %0 succesfully deleted' => "%0 başlıklı not başarı ile silindi",	//%0 is note title
	'Note %0 not exists' => "%0 başlıklı not silinemedi ",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Dosya geri getirilemeyecek şekilde silinecektir. Devam ?",	
	'Private notes' => "Özel Notlar",	
	'There are no private notes' => "Hiç Özel Notunuz yok",	
	'Public notes' => "Genel Notlar",	
	'There are no public notes' => "Hiç Genel Notunuz yok",	
	'Editing note' => "Not düzenleniyor",	
	'Last changed by %0 at %1' => "En son %0 tarafından %1 tarihinde değiştirildi",	//%0 is note author, %1 is the date
	'Title' => "Başlık",	
	'Status' => "Durum",	
	'Public' => "Genel",
	'Private' => "Özel",
	'New note' => "Yeni Not",
),
'portuguese' => array (
	'Note %0 succesfully saved' => 'Nota %0 salva com sucesso',	 //%0 is note title
	'Some fields were not completed' => "Existem campos imcompletos",	
	'Note %0 succesfully deleted' => "Nota %0 eliminada com sucesso",	//%0 is note title
	'Note %0 not exists' => "Nota %0 não existe",	//%0 is note title
	'File will be permanently deleted. Continue?' => "A nota irá ser permanentemente eliminada. Continuar?",	
	'Private notes' => "Notas privadas",	
	'There are no private notes' => "Não existem notas privadas",	
	'Public notes' => "Notas públicas",	
	'There are no public notes' => "Não existem notas públicas",	
	'New note' => "Nova nota",	
	'Editing note' => "Editar nota",	
	'Last changed by %0 at %1' => "Ultima alteração feita a %1 por %0",	//%0 is note author, %1 is the date
	'Title' => "Título",	
	'Status' => "Status",	
	'Public' => "Público",
	'Private' => "Privado",
	'New note' => "Nova nota",
),
'swedish' => array (
	'Copy to Home as HTML file' => "Kopiera till din hemkatalog som html-fil",  
	'Note %0 succesfully saved' => 'Anteckningen %0 sparades',	 //%0 is note title
	'Some fields were not completed' => "Några fält fyldes inte i",	
	'Note %0 succesfully deleted' => "Anteckningen %0 raderades",	//%0 is note title
	'Note %0 not exists' => "Anteckningen %0 finns inte",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Filen kommer att raderas permanent. Vill du fortsätta?",	
	'Private notes' => "Privata anteckningar",	
	'There are no private notes' => "Det finns inga privata anteckningar",	
	'Public notes' => "Offentliga anteckningar",	
	'There are no public notes' => "Det finns inga offentliga anteckningar",	
	'New note' => "Ny anteckning",	
	'Editing note' => "Redigerar anteckning",	
	'Last changed by %0 at %1' => "Senast ändrad av %0 kl %1",	//%0 is note author, %1 is the date
	'Title' => "Titel",	
	'Status' => "Status",	
	'Public' => "Offentlig",
	'Private' => "Privat",
	'New note' => "Ny anteckning",
),
'chinese' => array (
	'Copy to Home as HTML file' => "复制为HTML文件",  
	'Note %0 succesfully saved' => '%0已成功保存',	 //%0 is note title
	'Some fields were not completed' => "一些文件不全面",	
	'Note %0 succesfully deleted' => "%0已成功删除",	//%0 is note title
	'Note %0 not exists' => "%0不存在",	//%0 is note title
	'File will be permanently deleted. Continue?' => "文件将被永久删除，确定吗？",	
	'Private notes' => "私人记事",	
	'There are no private notes' => "没有私人记事",	
	'Public notes' => "开放记事",	
	'There are no public notes' => "没有开放记事",	
	'New note' => "新建记事",	
	'Editing note' => "编辑日记",	
	'Last changed by %0 at %1' => "%0到%1最近的更新",	//%0 is note author, %1 is the date
	'Title' => "标题",	
	'Status' => "",	
	'Public' => "公开",
	'Private' => "私人",
	'New note' => "新建记事",
),
'dutch' => array (
	'Copy to Home as HTML file' => "Als HTML naar eigen map kopieëren",  
	'Note %0 succesfully saved' => "Notitie %0 succesvol bewaard",	 //%0 is note title
	'Some fields were not completed' => "Sommige velden waren niet ingevuld",	
	'Note %0 succesfully deleted' => "Notitie %0 succesvol verwijderd",	//%0 is note title
	'Note %0 not exists' => "Notitie %0 bestaat niet",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Bestand wordt voorgoed verwijderd. Doorgaan?",
	'Private notes' => "Privé Notities",
	'There are no private notes' => "Geen privé notities gevonden",	
	'Public notes' => "Publieke notities",	
	'There are no public notes' => "Geen publieke notities gevonden",
	'New note' => "Nieuwe notitie",	
	'Editing note' => "Notitie wordt bewerkt",	
	'Last changed by %0 at %1' => "Laatste wijziging door %0 op %1",	//%0 is note author, %1 is the date
	'Title' => "Titel",	
	'Status' => "Status",	
	'Public' => "Publiek",
	'Private' => "Privé",
	'New note' => "Nieuwe notitie",
),
'hungarian' => array (
	'Copy to Home as HTML file' => "Másolás a Fő könyvtárba HTML fájlként",  
	'Note %0 succesfully saved' => '%0 jegyzet sikeresen lementve',	 //%0 is note title
	'Some fields were not completed' => "Nem minden mező lett kitöltve",	
	'Note %0 succesfully deleted' => " %0 jegyzet sikeresen törölve",	//%0 is note title
	'Note %0 not exists' => "%0 jegyzet nem létezik",	//%0 is note title
	'File will be permanently deleted. Continue?' => "A fájl véglegesen törölve lesz. Folytatja?",	
	'Private notes' => "Privát jegyzetek",	
	'There are no private notes' => "Nincsenek privát jegyzetek",	
	'Public notes' => "Nyilvános jegyzetek",	
	'There are no public notes' => "Nincsenek nyilvános jegyzetek",	
	'New note' => "Új jegyzet",	
	'Editing note' => "Jegyzet szerkesztése",	
	'Last changed by %0 at %1' => "",	//%0 is note author, %1 is the date
	'Title' => "Cím",	
	'Status' => "Állapot",	
	'Public' => "Nyilvános",
	'Private' => "Privát",
	'New note' => "Új jegyzet",
),
'italian' => array (
	'Copy to Home as HTML file' => "Copia in Home come file HTML",  
	'Note %0 succesfully saved' => 'Nota %0 salvata',	 //%0 is note title
	'Some fields were not completed' => "Alcuni campi non sono stati completati",	
	'Note %0 succesfully deleted' => "Nota %0 cancellata",	//%0 is note title
	'Note %0 not exists' => "La Nota %0 non esiste",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Il file sarà cancellato. Continuo?",	
	'Private notes' => "Nota privata",	
	'There are no private notes' => "Non ci sono Note private",	
	'Public notes' => "Note pubbliche",	
	'There are no public notes' => "Non ci sono note pubbliche",	
	'New note' => "Nuova Nota",	
	'Editing note' => "Edita la Nota",	
	'Last changed by %0 at %1' => "Ultimo cambiamento di %0 il %1",	//%0 is note author, %1 is the date
	'Title' => "Titolo",	
	'Status' => "Stato",	
	'Public' => "Pubblico",
	'Private' => "Privato",
	'New note' => "Nuova Nota",
),
'russian' => array (
	'Copy to Home as HTML file' => "Копировать в домашнюю папку как HTML",  
	'Note %0 succesfully saved' => 'Записка %0 сохранена',	 //%0 is note title
	'Some fields were not completed' => "Некоторые поля не заполнены",	
	'Note %0 succesfully deleted' => "Записка %0 удалена",	//%0 is note title
	'Note %0 not exists' => "Записка %0 не существует",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Файл будет удален. Продолжить?",	
	'Private notes' => "Приватные записки",	
	'There are no private notes' => "Нет приватных записок",	
	'Public notes' => "Публичные записки",	
	'There are no public notes' => "Нет публичных записок",	
	'New note' => "Новая записка",	
	'Editing note' => "Редактирование",	
	'Last changed by %0 at %1' => "Последнее изменение от %0 в %1",	//%0 is note author, %1 is the date
	'Title' => "Название",	
	'Status' => "Статус",	
	'Public' => "Публичная",
	'Private' => "Приватная",
	'New note' => "Новая записка",
),
'danish' => array (
	'Copy to Home as HTML file' => "Kopiere til hjemmemappe som html dokument",  
	'Note %0 succesfully saved' => 'Notat %0 blev gemt',       //%0 is note title
	'Some fields were not completed' => "Nogle felter var ikke udfyldt korrekt", 
	'Note %0 succesfully deleted' => "Notat %0 blev slettet",    //%0 is note title
	'Note %0 not exists' => "Notat %0 findes ikke",     //%0 is note title
	'File will be permanently deleted. Continue?' => "Filen vil blive permanent slettet, ønsker du at fortsætte?",    
	'Private notes' => "Private notater",  
	'There are no private notes' => "Der er ingen private notater",     
	'Public notes' => "Offentlige notater",   
	'There are no public notes' => "Der er ingen offentlige notater",      
	'New note' => "Nyt notat",       
	'Editing note' => "Rediger notat",   
	'Last changed by %0 at %1' => "Sidst ændret af %0 - %1",       //%0 is note author, %1 is the date
	'Title' => "Titel",  
	'Status' => "Status", 
	'Public' => "Offentlig",
	'Private' => "Privat",
	'New note' => "Nyt notat",
),
'finnish' => array (
	'Copy to Home as HTML file' => "Kopioi",  
	'Note %0 succesfully saved' => 'Merkintä %0 tallennettiin onnistunesti',	 //%0 is note title
	'Some fields were not completed' => "Joitakin kenttiä ei ole täytetty",	
	'Note %0 succesfully deleted' => "Merkintä %0 poistettiin onnistuneesti",	//%0 is note title
	'Note %0 not exists' => "Merkintää %0 ei ole",	//%0 is note title
	'File will be permanently deleted. Continue?' => "Tiedosto poistetaan pysyvästi. Jatkatako?",	
	'Private notes' => "Yksityiset merkinnät",	
	'There are no private notes' => "Ei ole yksityisiä merkintöjä",	
	'Public notes' => "Julkiset muistiinpanot",	
	'There are no public notes' => "Ei ole julkisia merkintöjä",	
	'New note' => "Uusi merkintä",	
	'Editing note' => "Merkintää editoidaan",	
	'Last changed by %0 at %1' => "Viimeksi muutettu %0:n toimesta %1 ",	//%0 is note author, %1 is the date
	'Title' => "Otsikko",	
	'Status' => "Tila",	
	'Public' => "Julkinen",
	'Private' => "Yksityinen",
	'New note' => "Uusi merkintä",
),
'romanian' => array (
	'Copy to Home as HTML file' => "Copiaza in Home ca fisier HTML'",  
	'Note %0 succesfully saved' => 'Nota %0 a fost salvata' , //%0 is note title
	'Some fields were not completed' => 'Cateva spatii nu au fost completate' ,
	'Note %0 succesfully deleted' => 'Nota %0 a fost stearsa' ,//%0 is note title
	'Note %0 not exists' => 'Nota %0 nu exista' ,//%0 is note title
	'File will be permanently deleted. Continue?' => 'Fisierul va fi sters definitiv. Esti sigur ca vrei sa continui?' ,
	'Private notes' => 'Note private' ,
	'There are no private notes' => 'Aici nu exista note private' ,
	'Public notes' => 'Note publice' ,
	'There are no public notes' => 'Aici nu exista note publice' ,
	'New note' => 'Nota noua' ,
	'Editing note' => 'Nota se editeaza' ,
	'Last changed by %0 at %1' => 'Ultima oara a fost modificat de %0 la %1' ,//%0 is note author, %1 is the date
	'Title' => "Titlu",
	'Status' => 'Statistici',
	'Public' => "Public",
	'Private' => "Privat",
	'New note' => "Nota noua"
),


);

   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
