<?PHP
/* Application language file 
   */
   
$AppLanguages = array (
'english' => array (), // 7 strings
'arabic' => array ( // 3 strings
	"Add feed" => "عنوان جديد للنشرات",
	"show" => "رؤية",
	"Delete" => "مسح",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'bahasa melayu' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'bangla' => array ( // 3 strings
	"Add feed" => "Feed যোগ কর",
	"show" => "দেখাও",
	"Delete" => "মুছে ফেল",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'brasileiro/português' => array ( // 3 strings
	"Add feed" => "Adicionar feed",
	"show" => "mostrar",
	"Delete" => "Apagar",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'bulgarian' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'català' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'český' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'chinese' => array ( // 3 strings
	"Add feed" => "增加RSS種子",
	"show" => "展示",
	"Delete" => "刪除",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'croatian' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'dansk' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'deutsch' => array ( // 7 strings
	"Add feed" => "Feed hinzufügen",
	"show" => "Anzeigen",
	"Delete" => "Löschen",
	"Clock format" => "Uhr-Format",
	"Show headlines only" => "Nur Kopfzeilen anzeigen",
	"Open items in new browser window instead of eyeNav" => "Links in neuem Fenster öffnen",
	"Maximum number of articles to show\n(0 for unlimited)" => "Maximal angezeigte Artikel (0=unendlich)",
),
'español' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'euskara' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'français' => array ( // 3 strings
	"Add feed" => "Ajouter un flux",
	"show" => "Afficher",
	"Delete" => "Effacer",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'galego' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'greek' => array ( // 3 strings
	"Add feed" => "Προσθήκη πηγής",
	"show" => "εμφάνιση",
	"Delete" => "Διαγραφή",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'italiano' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'japanese' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'korean' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'magyar' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'nederlands' => array ( // 3 strings
	"Add feed" => "Feed toevoegen",
	"show" => "tonen",
	"Delete" => "Verwijderen",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'norsk' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'polski' => array ( // 1 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "Usuń",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'português' => array ( // 3 strings
	"Add feed" => "Adicionar fonte",
	"show" => "Mostrar",
	"Delete" => "Eliminar",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'românesc' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'russian' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'slovenský' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'suomalainen' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'svensk' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'türk' => array ( // 3 strings
	"Add feed" => "Yeni akım ekle",
	"show" => "Göster",
	"Delete" => "Sil",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'ukrainian' => array ( // 3 strings
	"Add feed" => "Додати стрічку",
	"show" => "Показати",
	"Delete" => "Видалити",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
'việt' => array ( // 0 strings
	"Add feed" => "",
	"show" => "",
	"Delete" => "",
	"Clock format" => "",
	"Show headlines only" => "",
	"Open items in new browser window instead of eyeNav" => "",
	"Maximum number of articles to show\n(0 for unlimited)" => "",
),
);
   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
