<?PHP
/* Application language file 
   */
   
$AppLanguages = array (
'catalan' => array (
	'Your Home dir is empty' => "El teu directori és buit",
	'File uploaded' => "Arxiu pujat",
	'File already exists' => "L'arxiu ja existeix",
	'File moved to trash' => "Arxiu mogut a la paperera",
	'Image' => "Imatge",
	'Your files' => "Els teus arxius",
	'Upload a file' => "Puja un arxiu",
	'File to upload' => "Arxiu a pujar",
	'Upload' => "Pujar",
	'Actions' => "Accions",
	'New Document' => "Nou Document",
	'New Message' => "Nou Missatge",
	'New Contact' => "Nou Contacte",
	'Install Application' => "Instal·lar una nova aplicació",
	'Notifications' => "Avisos",
	'New Messages' => "Hi ha nous missatges",
	'No new Messages' => "No hi ha nous missatges",
	'New Folder' => "Nova carpeta",
	'Upload a File' => "Pujar un arxiu",
	'My Home' => "Els meus arxius",
	'Public Files' => "Arxius públics",
	'Create a new directory' => "Crea una nova carpeta",
	'Sites' => "Llocs",
	'This directory is empty' => "Aquest directori és buit",
	'Cancel' => "Tancar",
	'New directory created' => "Nou directori creat",
	'Directory removed' => "Directori esborrat",
	'The directory is not empty' => "El directori no és buit",
	'Copy to Public' => "Copiar a públic",

),
'spanish' => array (
	'Your Home dir is empty' => 'Tu directorio está vacío',
	'File uploaded' => 'Archivo subido',
	'File already exists' => 'El archivo ya existe',
	'File moved to trash' => 'Archivo movido a la papelera',
	'Image' => 'Imagen',
	'Your files' => 'Tus archivos',
	'Upload a file' => 'Subir un archivo',
	'File to upload' => 'Archivo a subir',
	'Upload' => 'Subir',
	'Actions' => "Acciones",
	'New Document' => "Nuevo Documento",
	'New Message' => "Nuevo Mensaje",
	'New Contact' => "Nuevo Contacto",
	'Install Application' => "Instalar una nueva aplicación",
	'Notifications' => "Avisos",
	'New Messages' => "Hay nuevos mensajes",
	'No new Messages' => "No hay nuevos mensajes",
	'New Folder' => "Nueva carpeta",
	'Upload a File' => "Subir un archivo",
	'My Home' => "Mis archivos",
	'Public Files' => "Archivos públicos",
	'Create a new directory' => "Crea una nueva carpeta",
	'Sites' => "Sitios",
	'This directory is empty' => "Este directorio está vacío",
	'Cancel' => "Cerrar",
	'New directory created' => "Nuevo directorio creado",
	'Directory removed' => "Directorio borrado",
	'The directory is not empty' => "El directorio no está vacío",
	'Copy to Public' => "Copiar a público",



),
'bulgarian' => array (
	'Your Home dir is empty' => "Домашната Ви директтория е празна",
	'File uploaded' => "Файлът е качен",
	'File already exists' => "Файлът вече съществува",
	'File moved to trash' => "Файлът е преместен в кошчето",
	'Image' => "Изображение",
	'Your files' => "Вашите файлове",
	'Upload a file' => "Качване на файл",
	'File to upload' => "Файл за качване",
	'Upload' => "Качване",
	'Actions' => "Действия",
	'New Document' => "Нов документ",
	'New Message' => "Ново съобщение",
	'New Contact' => "Нов контакт",
	'Install Application' => "Инсталиране на ново приложение",
	'Notifications' => "Известия",
	'New Messages' => "Нови съобщения",
	'No new Messages' => "Няма нови съобщения",
),
'polish' => array (
	'Your Home dir is empty' => "Twój katalog domowy jest pusty",
	'File uploaded' => "Plik został wgrany",
	'File already exists' => "Plik już istnieje",
	'File moved to trash' => "Plik został przeniesiony do kosza",
	'Image' => "Obrazek",
	'Your files' => "Twoje pliki",
	'Upload a file' => "Wgraj plik",
	'File to upload' => "Pliki do wgrania",
	'Upload' => "Wgraj",
	'Actions' => "Akcje",
	'New Document' => "Nowy dokument",
	'New Message' => "Nowa wiadomość",
	'New Contact' => "Nowy Kontakt",
	'Install Application' => "Instaluj aplikacje",
	'Notifications' => "Powiadomienia",
	'New Messages' => "Nowe wiadomości",
	'No new Messages' => "Brak nowych wiadomości",
),
'french' => array (
	'Your Home dir is empty' => "Votre répertoire personnel est vide",
	'File uploaded' => "Fichier téléchargé",
	'File already exists' => "Le fichier existe déja",
	'File moved to trash' => "Fichier déplacé dans la corbeille",
	'Image' => "Image",
	'Your files' => "Vos fichiers",
	'Upload a file' => "Télécharger un fichier",
	'File to upload' => "Fichier à télécharger",
	'Upload' => "Télécharger",
	'Actions' => "Actions",
	'New Document' => "Nouveau Document",
	'New Message' => "Nouveau Message",
	'New Contact' => "Nouveau Contact",
	'Install a new application' => "Installer une nouvelle application",
	'Notifications' => "Avis",
	'New Messages' => "Nouveaux Messages",
	'No new Messages' => "Pas de nouveaux Messages",
),
'german' => array (
	'Your Home dir is empty' => "Ihr Verzeichnis ist leer",
	'File uploaded' => "Datei hochgeladen",
	'File already exists' => "Datei exitiert bereits",
	'File moved to trash' => "Datei in den Papierkorb verschoben",
	'Image' => "Bild",
	'Your files' => "Ihre Dateien",
	'Upload a file' => "Datei hochladen",
	'File to upload' => "Hochzuladende Datei",
	'Upload' => "Upload",
),
'turkish' => array (
	'Your Home dir is empty' => "Ev Dizininiz boş",
	'File uploaded' => "Dosya Yollandı",
	'File already exists' => "Dosya zaten mevcut",
	'File moved to trash' => "Dosya çöp kutusuna taşındı",
	'Image' => "Resim",
	'Your files' => "Dosyalarınız",
	'Upload a file' => "Dosya Gönderimi",
	'File to upload' => "Gönderilecek Dosya",
	'Upload' => "Gönder",
),
'portuguese' => array (
	'Your Home dir is empty' => "O seu diretório Home está vazio",
	'File uploaded' => "Documento inserido",
	'File already exists' => "O documento já existe",
	'File moved to trash' => "Documento movido para a lixeira",
	'Image' => "Imagem",
	'Your files' => "Documentos",
	'Upload a file' => "Inserir um documento",
	'File to upload' => "Documento a ser inserido",
	'Upload' => "Inserir",
),
'swedish' => array (
	'Your Home dir is empty' => "Din hemkatalog är tom",
	'File uploaded' => "Filen laddades upp",
	'File already exists' => "Filen finns redan",
	'File moved to trash' => "Filen flyttades till papperskorgen",
	'Image' => "Bild",
	'Your files' => "Dina filer",
	'Upload a file' => "Ladda upp en fil",
	'File to upload' => "Fil att ladda upp",
	'Upload' => "Ladda upp",
),
'chinese' => array (
	'Your Home dir is empty' => "你的首页目录为空",
	'File uploaded' => "文件上传完毕",
	'File already exists' => "文件已存在",
	'File moved to trash' => "文件移动到回收站",
	'Image' => "图片",
	'Your files' => "你的文件",
	'Upload a file' => "上传一个文件",
	'File to upload' => "上传的文件",
	'Upload' => "上传",
),
'dutch' => array (
	'Your Home dir is empty' => "Je documenten map is leeg",
	'File uploaded' => "Bestand ge-upload",
	'File already exists' => "Bestand bestaat al",
	'File moved to trash' => "Bestand naar prullenbak verplaatst",
	'Image' => "Afbeelding",
	'Your files' => "Jouw bestanden",
	'Upload a file' => "Bestand uploaden",
	'File to upload' => "Te uploaden bestand",
	'Upload' => "Uploaden",
),
'hungarian' => array (
	'Your Home dir is empty' => "A Fő könyvtárad üres",
	'File uploaded' => "Fájl feltöltve",
	'File already exists' => "A fájl már létezik",
	'File moved to trash' => "Fájl a Lomtárba helyezve",
	'Image' => "Kép",
	'Your files' => "Saját fájlok",
	'Upload a file' => "Fájl feltöltése",
	'File to upload' => "Fájl, amit feltöltesz",
	'Upload' => "Feltöltés",
),
'italian' => array (
	'Your Home dir is empty' => "La tua Home dir è vuota",
	'File uploaded' => "File caricato",
	'File already exists' => "Il file esiste",
	'File moved to trash' => "Il file è stato spostato nel cestino",
	'Image' => "Immagine",
	'Your files' => "I tuoi files",
	'Upload a file' => "Carica un file",
	'File to upload' => "File da caricare",
	'Upload' => "Carica",
),
'russian' => array (
	'Your Home dir is empty' => "Ваша домашняя папка пуста",
	'File uploaded' => "Файл залит",
	'File already exists' => "Файл уже существует",
	'File moved to trash' => "Файл выброшен в мусорник",
	'Image' => "Картинка",
	'Your files' => "Ваши файлы",
	'Upload a file' => "Залить файл",
	'File to upload' => "Файл на заливку",
	'Upload' => "Залить",
),
'danish' => array (
	'Your Home dir is empty' => "Din hjemmemappe er tom",
	'File uploaded' => "Filen er uploaded",
	'File already exists' => "Filen eksistere allerede",
	'File moved to trash' => "Filen blev flyttet til Affaldspanden",
	'Image' => "Billede",
	'Your files' => "Mine Filer",
	'Upload a file' => "Upload en fil",
	'File to upload' => "Vælg filen der skal uploades",
	'Upload' => "Upload",
),
'finnish' => array (
	'Your Home dir is empty' => "Kotihakemistosi on tyhjä",
	'File uploaded' => "Tiedosto on lähetetty",
	'File already exists' => "Tiedosto on jo olemassa",
	'File moved to trash' => "Tiedosto on siirretty roskakoriin",
	'Image' => "Kuva",
	'Your files' => "Tiedostosi",
	'Upload a file' => "Lähetä tiedosto",
	'File to upload' => "Lähetettävä tiedosto",
	'Upload' => "Lähetä",
),
'romanian' => array (
	'Your Home dir is empty' => "Directorul Home este gol",
	'File uploaded' => "Fisier uploadat",
	'File already exists' => "Fisierul exista deja",
	'File moved to trash' => "Fisierul a fost sters",
	'Image' => "Imagine",
	'Your files' => "Fisierele tale",
	'Upload a file' => "Incarca un fisier",
	'File to upload' => "Fisier catre uploadare",
	'Upload' => "Incarca",
	'Actions' => "Actiuni",
	'New Document' => "Document nou",
	'New Message' => "Mesaj nou",
	'New Contact' => "Contact nou",
	'Install Application' => "Instaleaza un program nou",
	'Notifications' => "Note",
	'New Messages' => "Mesaje noi",
	'No new Messages' => "Nu sunt mesaje noi",
),
);
   global $Translations;
   if (isset ($AppLanguages[$select = !empty ($_SESSION['lang']) ? $_SESSION['lang'] : DEFAULTLANG]))
      $Translations = array_merge ($Translations, $AppLanguages[$select]);   
?>
