<?PHP
if (!defined('SYSINFO')) exit;
if (isset($_REQUEST['ll'])) $lang = strip_tags($_REQUEST['ll']);
else $lang = substr($_SERVER["HTTP_ACCEPT_LANGUAGE"], 0, 2);

switch ($lang) {
	case "ca" :
		$llang = "catalan";
		$log_were = "Ja som";
		$log_uac = "usuaris i comptant!";
		$log_org = "organitza't";
		$log_org2 = "Calendari, Agenda, Lector de RSS, Marcadors...";
		$log_prod = "sigues productiu";
		$log_prod2 = "Processador de Textes, Missatgeria, Geolocalizació...";
		$log_entr = "entretén-te";
		$log_entr2 = "Reproductor de música i vídeo, Galeríes, Jocs...";
		$log_conn = "connecta't";
		$log_conn2 = "Xat, Marcadors socials, Taulell Públic...";
		$log_Username = "Usuari";
		$log_Password = "Contrasenya";
		$log_Language = "Idioma";
		$log_create = "crea un nou compte";
		$log_Email = "E-mail";
		$log_text1 = "Benvingut a";
		$log_text2 = "on pots crear i utilitzar el teu propi Escriptori Virtual eyeOS. Per saber més sobre el projecte, vine a formar part de la comunitat visitant la <a href='http://www.eyeos.org'>web principal d'eyeOS</a>.";
		$log_text3 = "Amb";
		$log_text4 = "tots els teus arxius estan a tot arreu, allà on tu estiguis, sempre que hi hagi un navegador d'Internet.";
		$log_butcreate = "crear";
		$log_butsignin = "entrar";
	break;
	case "de" :
		$llang = "german";
		$log_were = "Wir sind";
		$log_uac = "Benutzer und Zählen!";
		$log_org = "sei organisiert";
		$log_org2 = "Kalendar, Agenda, RSS Reader, Lesezeichen...";
		$log_prod = "sei produktiv";
		$log_prod2 = "Textbearbeitung, Nachrichtensystem...";
		$log_entr = "sei unterhalten";
		$log_entr2 = "Musik und Video Player, Bilder Gallerien, Spiele...";
		$log_conn = "sei verbunden";
		$log_conn2 = "Chat, geteilte Lesezeichen, öffentliches Forum...";
		$log_Username = "Benutzername";
		$log_Password = "Passwort";
		$log_Language = "Sprache";
		$log_create = "Neuer Account";
		$log_Email = "E-mail";
		$log_text1 = "Willkommen zu";
		$log_text2 = "hier kannst du deinen persönlcihen eyeOS Desktop einrichten und verwalten. Um mehr über eyeOS und die dahintersteckende Community zu erfahren, besuch einfach die <a href='http://www.eyeos.org'>eyeOS Webseite</a>.";
		$log_text3 = "Mit";
		$log_text4 = "sind deine Daten überall aus dem Internet jederzeit mit einem der gängigen Standard-Browser zu erreichen.";
		$log_butcreate = "Fertig";
		$log_butsignin = "Einloggen";
	break;
	case "es" :
		$llang = "spanish";
		$log_were = "Ya somos";
		$log_uac = "usuarios y contando!";
		$log_org = "organízate";
		$log_org2 = "Calendario, Agenda, Lector de RSS, Favoritos...";
		$log_prod = "sé productivo";
		$log_prod2 = "Procesador de Textos, Mensajería, Geolocalización...";
		$log_entr = "entretente";
		$log_entr2 = "Reproductor de música y video, Galerías, Juegos...";
		$log_conn = "conéctate";
		$log_conn2 = "Chat, Marcadores sociales, Tablón Público...";
		$log_Username = "Usuario";
		$log_Password = "Contraseña";
		$log_Language = "Idioma";
		$log_create = "crea una nueva cuenta";
		$log_Email = "E-mail";
		$log_text1 = "Bienvenido a";
		$log_text2 = "donde puedes crear y usar tu propio Escritorio Virtual eyeOS. Para saber más sobre eyeOS, ven a formar parte de la comunidad visitando la <a href='http://www.eyeos.org'>web principal de eyeOS</a>.";
		$log_text3 = "Con";
		$log_text4 = "todos tus archivos están en todos lados, allí donde estés, siempre que haya un navegador de Internet.";
		$log_butcreate = "crear";
		$log_butsignin = "entrar";
	break;
	case "fr" :
		$llang = "french";
		$log_were = "Nous sommes";
		$log_uac = "utilisateurs et ca continue!";
		$log_org = "Soyez organisé";
		$log_org2 = "Calendrier, Agenda, Lecteur RSS, Favoris...";
		$log_prod = "Soyez productif";
		$log_prod2 = "Traitement de texte, Messagerie, Geolocalisation...";
		$log_entr = "Divertissez-vous";
		$log_entr2 = "Lecteur de musique et vidéo, Albums Photos, Jeux...";
		$log_conn = "Soyez connecté";
		$log_conn2 = "Chat, Réseau social, Forums publics...";
		$log_Username = "Nom d'utilisateur";
		$log_Password = "Mot de passe";
		$log_Language = "Langue";
		$log_create = "créer un nouveau compte";
		$log_Email = "E-mail";
		$log_text1 = "Bienvenue à";
		$log_text2 = "Où vous pouvez créer et utiliser votre propre bureau virtuel EyeOS. Pour en savoir plus sur EyeOS, joignez notre communauté en visitant le <a href='http://www.eyeos.org'>site web de EyeOS</a>.";
		$log_text3 = "Avec";
		$log_text4 = "toutes vos données sont accessibles où que vous soyez avec une connexion internet et un navigateur compatible avec les standards.";
		$log_butcreate = "Créer";
		$log_butsignin = "identifier";
	break;
	case "si" :
		$llang = "slovenian";
		$log_were = "Mi smo";
		$log_uac = "uporabnikov in vedno narascajoce!";
		$log_org = "ostati organiziran";
		$log_org2 = "Calendar, Agenda, RSS Reader, Bookmarks...";
		$log_prod = "ostati produktiven";
		$log_prod2 = "urejevalnik besedil, sistem obvescanja, Geolocation...";
		$log_entr = "ostali v zabavi";
		$log_entr2 = "predvajalniki glasbe in videa, foto galerije, igre...";
		$log_conn = "ostati povezan";
		$log_conn2 = "Chat, Social Bookmarking, Public Board...";
		$log_Username = "Uporabnisko ime";
		$log_Password = "Geslo";
		$log_Language = "Jezik";
		$log_create = "ustvarite nov racun";
		$log_Email = "E-mail";
		$log_text1 = "Dobrodosli v ";
		$log_text2 = "kjer si lahko ustvarite svojo navidezno eyeOS namizje. Za vec informacij o eyeOS, se prikljucite nasi skupini z obiskom glavne strani <a href='http://www.eyeos.org'>eyeOS-a</a>.";
		$log_text3 = "Z";
		$log_text4 = "so vsi vasi podatki dostopni povsod, kjer imate dostop do interneta s standardnim brskalnikom.";
		$log_butcreate = "ustvari";
		$log_butsignin = "prijava";
	break;
	case "fi" :
		$llang = "finnish";
		$log_were = "Meitä on jo";
		$log_uac = "käyttäjää, lisää liittyy koko ajan!";
		$log_org = "Ajankäyttö";
		$log_org2 = "Kalenteri, työjärjestys, RSS lukija, kirjanmerkit...";
		$log_prod = "Viestintä";
		$log_prod2 = "tekstinhallinta, internet viestintä, sijainti...";
		$log_entr = "Ajanviete";
		$log_entr2 = "Musiikki- ja videosoitin, valokuvakansiot, pelejä...";
		$log_conn = "Verkostoidu";
		$log_conn2 = "Neuvottele verkossa, yhteiset kirjanmerkit, ilmoitustaulu...";
		$log_Username = "Käyttäjänimi";
		$log_Password = "Salasana";
		$log_Language = "Valitse kieli";
		$log_create = "Luo uusi tili...";
		$log_Email = "Sähköposti";
		$log_text1 = "Tervetuloa";
		$log_text2 = "jossa voit käyttää omaa virtuaalista työpöytää. Opi enemmän liittymllä yhteisöömme. Käy  <a href='http://www.eyeos.org'>eyeOS verkkosivustolla</a>.";
		$log_text3 = "Ota käyttöön";
		$log_text4 = ", niin tarvisemasi tieto on käytössä siellä, missä pääset Internet verkkoon ja käytät standardin mukaista selainta.";
		$log_butcreate = "lähetä";
		$log_butsignin = "kirjaudu";
	break;
	case "bg" :
		$llang = "bulgarian";
		$log_were = "Не сме";
		$log_uac = "потребителя и се покачват!";
		$log_org = "бъди организиран";
		$log_org2 = "Календар, програма, RSS четец, отметки...";
		$log_prod = "бъдете продуктивни";
		$log_prod2 = "Текстов редактор, система за обмяна на съобщения, позициониране...";
		$log_entr = "забавлявайте се";
		$log_entr2 = "Плейъри за музика и видео, фото галерии, игри...";
		$log_conn = "бъдете свързани";
		$log_conn2 = "Чат, социални отметки, публични бюлетини...";
		$log_Username = "Потребител";
		$log_Password = "Парола";
		$log_Language = "Език";
		$log_create = "създаване на нов акаунт";
		$log_Email = "E-mail";
		$log_text1 = "Добре дошли в";
		$log_text2 = "където можете да създадете ваш собствен eyeOS виртуален работен плот. За да научите повече за eyeOS се присъединете към общността на основната <a href='http://www.eyeos.org'>eyeOS страница</a>.";
		$log_text3 = "С";
		$log_text4 = "всички данни са достъпни, там където имате Интернет връзка и съвместим със стандартите уеб браузър.";
		$log_butcreate = "създаване";
		$log_butsignin = "вход";
	break;
	case "ir" :
		$llang = "persian";
		$log_were = "ما هستیم";
		$log_uac = "کاربران در حال افزایش!";
		$log_org = "سازمان یافته شوید";
		$log_org2 = "تقویم ، برنامه ریزی ، خبر خوان ، سایت های برگزیده ، ...";
		$log_prod = "پر بار شوید";
		$log_prod2 = "پردازش کلمات ، سیستم پیام رسان ، موقعیت جغرافیایی ، ...";
		$log_entr = "سرگرم شوید";
		$log_entr2 = "پخش کننده موسیقی و فیلم ، مجموعه تصویر ، بازی ها ، ...";
		$log_conn = "متصل شوید";
		$log_conn2 = "گفتگو ، نشانه گذاری گروهی ، تابلوی عمومی ، ... ";
		$log_Username = "نام کاربری";
		$log_Password = "کلمه عبور";
		$log_Language = "زبان";
		$log_create = "ایجاد حساب جدید";
		$log_Email = "ایمیل";
		$log_text1 = "خوش آمدید به";
		$log_text2 = "جایی که میتوانید میزکار مجازی خود را بسازید و استفاده کنید. برای اطلاعات بیشتر درباره این برنامه عضو انجمن ما شوید برای این کار به <a href='http://www.eyeos.org'>eyeOS سایت</a> مراجعه کنید";
		$log_text3 = "با";
		$log_text4 = "تمام اطلاعات شما هر جایی که یک خط اینترنت و یک مرورگر آماده دارید در دسترس شما است.";
		$log_butcreate = "ایجاد";
		$log_butsignin = "ورود";
	break;
	case "bd" :
		$llang = "bangla";
		$log_were = "আমরা হনাম";
		$log_uac = "ব্যবাহারকারী এবং গণনা চলছে!";
		$log_org = "সংগঠিত হও";
		$log_org2 = "দিনপন্জী, এজেন্ডা, RSS পাঠক, বুকমার্ক...";
		$log_prod = "উৎপাদনশীল হও";
		$log_prod2 = "ওয়ার্ডপ্রসেসিং, মেসেজিং সিস্টেম, Geolocation...";
		$log_entr = "আমোদিত হএ";
		$log_entr2 = "সঙ্গীত এবং ভিডিও প্লেয়ার,ফটো গ্যালারী, গেমস...";
		$log_conn = "সংযুক্ত হও";
		$log_conn2 = "আড্ডা, সামাজিক Bookmarking, উন্মুক্ত বোর্ড...";
		$log_Username = "ব্যাবহারকারী";
		$log_Password = "পাসওয়ার্ড";
		$log_Language = "ভাষা";
		$log_create = "নতুন একাউন্ট তৈরী কর";
		$log_Email = "ই-মেইল";
		$log_text1 = "এ স্বাগতম";
		$log_text2 = "যেখানে আপনি আপনার নিজস্ব eyeOS ভার্চুয়াল ডেষ্কটপ তৈরী এবং ব্যাবহার করতে পারবেন । আরও জানতে আমাদের গোষ্ঠীতে যোগদিন এবং ভিজিট করুন <a href='http://www.eyeos.org'>eyeOS ওয়েবসাইট</a>.";
		$log_text3 = "এর সাহায্যে ";
		$log_text4 = "আপনার সমস্ত ডেটা সবসময় পাচ্ছেন শুধুমাত্র একটি standard ব্রাউজার এবং ইন্টারনেট সংযোগ থাকলেই।";
		$log_butcreate = "তৈরী কর";
		$log_butsignin = "সাইন-ইন";
	break;
	case "it" :
		$llang = "italian";
		$log_were = "Noi siamo";
		$log_uac = "utenti e conteggio!";
		$log_org = "essere organizzati";
		$log_org2 = "Calendario, Agenda, Lettore RSS, Segnalibri...";
		$log_prod = "essere produttivi";
		$log_prod2 = "Elaboratore di Testi, Messaggeria, Geolocalizzazione...";
		$log_entr = "divertirsi";
		$log_entr2 = "Riproduttore di Musica e Video, Gallerie Fotografiche, Giochi...";
		$log_conn = "essere connessi";
		$log_conn2 = "Chat, Segnalibri Sociali, Lavagna Pubblica...";
		$log_Username = "Nome Utente";
		$log_Password = "Password";
		$log_Language = "Lingua";
		$log_create = "crea un nuovo account";
		$log_Email = "E-mail";
		$log_text1 = "Benvenuti in";
		$log_text2 = "dove puoi creare e usare il tuo eyeOS Virtual Desktop. Per maggiori informazioni su eyeOS iscriviti alla nostra community sul <a href='http://www.eyeos.org'>sito ufficiale di eyeOS</a>.";
		$log_text3 = "Con";
		$log_text4 = "tutti i tuoi dati sono disponibili ovunque tu abbia un accesso ad internet ed un browser con i requisiti adatti.";
		$log_butcreate = "crea";
		$log_butsignin = "entra";
	break;

	default:
		$llang = "english";
		$log_were = "We're";
		$log_uac = "users and counting!";
		$log_org = "be organized";
		$log_org2 = "Calendar, Agenda, RSS Reader, Bookmarks...";
		$log_prod = "be productive";
		$log_prod2 = "Word Processor, Messaging System, Geolocation...";
		$log_entr = "be entertained";
		$log_entr2 = "Music and Video Player, Photo Galleries, Games...";
		$log_conn = "be connected";
		$log_conn2 = "Chat, Social Bookmarking, Public Board...";
		$log_Username = "Username";
		$log_Password = "Password";
		$log_Language = "Language";
		$log_create = "create a new account";
		$log_Email = "E-mail";
		$log_text1 = "Welcome to";
		$log_text2 = "where you can create and use your own eyeOS Virtual Desktop. To find out more about eyeOS join our community by visiting the main <a href='http://www.eyeos.org'>eyeOS website</a>.";
		$log_text3 = "With";
		$log_text4 = "all your data is available where ever you have Internet access and a standards compliant browser.";
		$log_butcreate = "create";
		$log_butsignin = "sign in";
	break;
}

?>
